Repository dotnet/wpf, pull requests merged in 2019-10, with the labels that each got.

#1987 Use Array.Empty
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass1.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass2.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/ExtendedPropertyCollection.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/Lasso.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Shaping/OpenTypeLayout.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/TextFormatting/FullTextLine.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Ink/Stroke2.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerData.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/PenThreadWorker.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispTabletDeviceCollection.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndPointerInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/textformatting/TextRunCache.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Annotations/Anchoring/TextViewSelectionProcessor.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Annotations/Anchoring/TreeNodeSelectionProcessor.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/IndexerPropertyInfo.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/LiveShapingList.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/PathParser.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Globalization/BamlTreeMap.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/RowParagraph.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsTable/RowSpanVector.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/FileDialog.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/SaveFileDialog.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/GridViewAutomationPeer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/GridViewCellAutomationPeer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/TreeViewAutomationPeer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/TabPanel.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TextAdaptor.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedSOMContainer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/PageContent.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/WpfKnownType.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Primitives/ElementMarkupObject.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Primitives/FrameworkElementFactoryMarkupObject.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/documents/PeoplePickerWrapper.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/MS/Internal/Printing/Configuration/WinSpoolPrinterCapabilities.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsEditBoxRange.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsRichEditRange.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/UnsupportedAutomationProxies/WindowsCalendar.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/Compoundfile/ContainerUtilities.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/Compoundfile/DataSpaceManager.cs
Labels: PR

#1947 Fix for issue 1883
  eng/copy-wpf.ps1
Labels: PR

#1986 Fix missing type forwards in reference assemblies
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/System.Xaml-ref-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/WindowsBase-ref-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/otherassemblyattrs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework-ref.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/otherassemblyattrs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/ref/PresentationUI-ref.csproj
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ValueSerializerAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/otherassemblyattrs.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/OtherAssemblyAttrs.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Collections/ObjectModel/ObservableCollection.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Collections/ObjectModel/ReadOnlyObservableCollection.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Collections/Specialized/INotifyCollectionChanged.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Collections/Specialized/NotifyCollectionChangedEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/WindowsBase.csproj
Labels: PR, issue-type-bug, tenet-compatibility

#2004 Ensure that markup compilation is run for all design time builds
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.targets
Labels: PR, ask-mode

#2006 Add `ThemeInfoAttribute` to application project templates
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/AssemblyInfo.cs
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/AssemblyInfo.vb
Labels: PR, ask-mode

#1999 Use correct PresentationBuildTasks.dll for VS and MSBuild builds
  eng/WpfArcadeSdk/tools/Pbt.props
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.props
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.targets
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj
Labels: PR

#2011 Fix missing type forwards in reference assemblies (3.0 port)
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/System.Xaml-ref-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/WindowsBase-ref-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/otherassemblyattrs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework-ref.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/otherassemblyattrs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/ref/PresentationUI-ref.csproj
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ValueSerializerAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/otherassemblyattrs.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/OtherAssemblyAttrs.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Collections/ObjectModel/ObservableCollection.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Collections/ObjectModel/ReadOnlyObservableCollection.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Collections/Specialized/INotifyCollectionChanged.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Collections/Specialized/NotifyCollectionChangedEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/WindowsBase.csproj
Labels: PR, Servicing-approved, area-servicing, tenet-compatibility

#2035 Update branding to preview2
  eng/Versions.props
Labels: PR

#1976 Adding border to ToggleButton when checked in high-contrast themes
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Aero/themes/Aero.NormalColor.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Aero2/Themes/Aero2.NormalColor.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.AeroLite/Themes/AeroLite.NormalColor.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Classic/Themes/Classic.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Luna/Themes/Luna.HomeStead.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Luna/Themes/Luna.Metallic.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Luna/Themes/Luna.NormalColor.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Royale/Themes/Royale.NormalColor.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/XAML/Button.xaml
Labels: PR, tenet-accessibility-mas

#2010 Fix missing type forwards in reference assemblies (3.1 port)
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/System.Xaml-ref-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/WindowsBase-ref-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/otherassemblyattrs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework-ref.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/otherassemblyattrs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/ref/PresentationUI-ref.csproj
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ValueSerializerAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/otherassemblyattrs.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/OtherAssemblyAttrs.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Collections/ObjectModel/ObservableCollection.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Collections/ObjectModel/ReadOnlyObservableCollection.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Collections/Specialized/INotifyCollectionChanged.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Collections/Specialized/NotifyCollectionChangedEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/WindowsBase.csproj
Labels: * NO MERGE *, PR, ask-mode, tenet-compatibility

#2051 Update config toolset with guards
  eng/WpfArcadeSdk/tools/Pbt.targets
  eng/configure-toolset.ps1
Labels: PR

#2065 Adding more guards in configure-toolset.ps1 to fix issues in publish steps
  eng/configure-toolset.ps1
Labels: PR

#2005 Add `ThemeInfoAttribute` to application project templates
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/AssemblyInfo.cs
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/AssemblyInfo.vb
Labels: PR

#2073 Change XPS document creation to use FileAccess.ReadWrite instead of FileAccess.Write.
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsDocument.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsManager.cs
Labels: PR, issue-type-bug, regression

#1977 Removing separators from SizeOfSet and PositionInSet counts
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/MenuItemAutomationPeer.cs
Labels: PR, tenet-accessibility-mas

#2075 [release/3.1] Use correct PresentationBuildTasks.dll for VS and MSBuild builds
  eng/WpfArcadeSdk/tools/Pbt.props
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.props
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.targets
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj
Labels: PR, Servicing-approved, ask-mode, auto_merge, issue-type-bug

#2111 Switch to label.N form for pre-release label
  eng/Versions.props
Labels: PR, auto_merge

#1761 Hit testing by geometry fails if more than one matrix trasformation is applied to a geometry.
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/HitTestWithGeometryDrawingContextWalker.cs
Labels: PR, issue-type-bug

#2097 Context Menus are sometimes not shown in High-DPI applications
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs
Labels: PR

#2100 Prevent NULL HWND's from being parented under SystemResources listener windows
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/HwndHost.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs
Labels: PR, issue-type-bug, issue-type-netfx-port

#2113 Update C++ Tools to VS16.3 Preview 4
  eng/Version.Details.xml
  eng/Versions.props
  eng/WpfArcadeSdk/tools/Pbt.props
  global.json
Labels: PR, Servicing-approved

#2092 Adding border to ToggleButton when checked in high-contrast themes
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Aero/themes/Aero.NormalColor.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Aero2/Themes/Aero2.NormalColor.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.AeroLite/Themes/AeroLite.NormalColor.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Classic/Themes/Classic.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Luna/Themes/Luna.HomeStead.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Luna/Themes/Luna.Metallic.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Luna/Themes/Luna.NormalColor.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Royale/Themes/Royale.NormalColor.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/XAML/Button.xaml
Labels: PR, Servicing-approved, issue-type-bug, tenet-accessibility-mas

#2090 Removing separators from SizeOfSet and PositionInSet counts
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/MenuItemAutomationPeer.cs
Labels: PR, Servicing-approved, issue-type-bug, tenet-accessibility-mas

#2098 [release/3.1] Context Menus are sometimes not shown in High-DPI applications
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs
Labels: PR, Servicing-approved, auto_merge, issue-type-netfx-port, regression

#2103 [Release/3.1] Hit testing by geometry fails if more than one matrix trasformation is applied to a geometry.
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/HitTestWithGeometryDrawingContextWalker.cs
Labels: PR, Servicing-approved, auto_merge, issue-type-bug

#2101 [release/3.1] Prevent NULL HWND's from being parented under SystemResources listener windows
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/HwndHost.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs
Labels: PR, Servicing-approved, auto_merge, issue-type-bug, issue-type-netfx-port

#2138 Increase .NET version to ensure we are using higher versions of NuGet
  eng/WpfArcadeSdk/Sdk/Sdk.props
  global.json
Labels: PR, area-infrastructure
