Repository dotnet/wpf, pull requests merged in 2019-11, with the labels that each got.

#2168 Fixup to WPF to adapt to removal of legacy API's from WinForms
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/System/Windows/Integration/ElementHost.cs
Labels: PR, ask-mode

#2181 Remove modification of MSBuildAllProjects property
  packaging/Microsoft.NET.Sdk.WindowsDesktop/Sdk/Sdk.props
  packaging/Microsoft.NET.Sdk.WindowsDesktop/Sdk/Sdk.targets
Labels: PR

#2191 Update PreReleaseVersionLabel to RTM
  eng/Versions.props
Labels: PR, auto_merge

#2203 add internal/release/3.* to PR trigger list
  azure-pipelines.yml
Labels: PR

#2204 add internal/release/3.* to PR trigger list
  azure-pipelines.yml
Labels: PR

#2202 Add internal/release/3.* to PR trigger
  azure-pipelines.yml
Labels: PR

#2210 Fixup pipelines for internal PR's to work
  eng/pipeline.yml
Labels: PR, tell-mode

#2209 Fixup pipelines for internal PR's to work
  eng/pipeline.yml
Labels: PR, tell-mode

#2211 Fixup pipelines for internal PR's to work
  eng/pipeline.yml
Labels: PR, auto_merge

#2230 Include "ResolveTargetingPackAssets" in AfterTargets; Remove unused Targets
  eng/WpfArcadeSdk/tools/SdkReferences.targets
Labels: PR

#2173 Add dotnet-eng and remove some other feeds
  NuGet.config
Labels: PR

#2241 Add internal/release/* to trigger
  azure-pipelines.yml
Labels: * NO MERGE *, PR, tell-mode

#2245 Typos and formatting
  Documentation/developer-guide.md
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/RichTextBox.cs
Labels: PR

#2251 Add internal ci triggers and clean up trigger list
  azure-pipelines.yml
Labels: PR

#2237 Fix typo
  packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj
Labels: PR
