Repository dotnet/wpf, pull requests merged in 2019-06, with the labels that each got.

#818 Change branding to preview 7
  eng/Versions.props
Labels: PR

#831 Remove pinned version of System.Memory
  eng/Version.Details.xml
  eng/Versions.props
  global.json
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj
Labels: PR

#833 Remove pinned version of system.memory
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj
Labels: PR

#862 Crash in DataGridItemAutomationPeer
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/GroupItemAutomationPeer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ItemsControlAutomationPeer.cs
Labels: PR

#794 Remove PresentationCore-CommonResources and move composite fonts to PresentationCore
  Microsoft.Dotnet.Wpf.sln
  eng/WpfArcadeSdk/tools/ShippingProjects.props
  eng/WpfArcadeSdk/tools/WpfProjectReference.targets
  src/Microsoft.DotNet.Wpf/cycle-breakers/PresentationFramework/PresentationFramework-ReachFramework-impl-cycle.csproj
  src/Microsoft.DotNet.Wpf/cycle-breakers/PresentationFramework/PresentationFramework-System.Printing-api-cycle.csproj
  src/Microsoft.DotNet.Wpf/cycle-breakers/PresentationFramework/PresentationFramework-System.Printing-impl-cycle.csproj
  src/Microsoft.DotNet.Wpf/cycle-breakers/PresentationUI/PresentationUI-PresentationFramework-impl-cycle.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationCore-CommonResources/PresentationCore-CommonResources.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationCore-CommonResources/dir.props
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Fonts/AnalyzeFont.txt
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Fonts/GlobalMonospace.CompositeFont
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Fonts/GlobalSansSerif.CompositeFont
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Fonts/GlobalSerif.CompositeFont
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Fonts/GlobalUserInterface.CompositeFont
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Fonts/andlso.ttf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Fonts/simpbdo.ttf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Fonts/simpfxo.ttf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Fonts/simpo.ttf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Fonts/tradbdo.ttf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Fonts/trado.ttf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FamilyCollection.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FontSource.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/ReachFramework/ReachFramework.csproj
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/ExternDll.cs
  src/Microsoft.DotNet.Wpf/src/System.Printing/ref/System.Printing-ref.csproj
Labels: PR, enhancement

#808 Add back ValueSerializerAttribute TypeForward to System.Xaml
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj
Labels: PR, bug

#868 Support `Microsoft.NetCore.App.Wpf` and `Microsoft.NetCore.App.WinForms` profiles in `Microsoft.NET.Sdk.WidnowsDesktop`
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
Labels: PR

#877 Suppress all GUI from IL(D)Asm calls.
  eng/WpfArcadeSdk/tools/InjectModuleInitializer.targets
Labels: PR, bug

#879 Don't generate ref assemblies for WPF extension assemblies
  src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemCore/PresentationFramework-SystemCore.csproj
  src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemData/PresentationFramework-SystemData.csproj
  src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemDrawing/PresentationFramework-SystemDrawing.csproj
  src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemXml/PresentationFramework-SystemXml.csproj
  src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemXmlLinq/PresentationFramework-SystemXmlLinq.csproj
Labels: PR

#882 Remove null reference workaround for PresentationFramework-SystemXmlLinq
  src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemXmlLinq/SystemXmlLinqExtension.cs
Labels: PR, bug

#888 fix helix target queues
  eng/helixpublish.proj
  eng/pipeline.yml
Labels: PR

#876 Update THIRD-PARTY-NOTICES.TXT
  THIRD-PARTY-NOTICES.TXT
Labels: PR

#750 Update to pool-provider sourced machines
  azure-pipelines.yml
Labels: PR

#881 Ensure that implicit references for .NET Framework projects are appropriate when targeting net3x and net40
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
Labels: PR

#899 port 2 changes from .NET 4.8: crash in PropertyChangeEventManager and GDI handle leak
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/ComponentModel/PropertyChangedEventManager.cs
Labels: PR, bug

#880 Enable APICompat in WPF Builds
  Documentation/api-compat.md
  eng/Version.Details.xml
  eng/Versions.props
  eng/WpfArcadeSdk/Sdk/Sdk.props
  eng/WpfArcadeSdk/Sdk/Sdk.targets
  eng/WpfArcadeSdk/tools/ApiCompat.props
  eng/WpfArcadeSdk/tools/ApiCompat.targets
  eng/WpfArcadeSdk/tools/FolderPaths.props
  global.json
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationBuildTasks-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationCore-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/ReachFramework-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/System.Printing-ref-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/System.Windows.Input.Manipulations-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/System.Xaml-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/UIAutomationClient-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/UIAutomationClientSideProviders-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/UIAutomationProvider-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/UIAutomationTypes-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/WindowsBase-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/src/System.Printing/ref/System.Printing.cs
Labels: PR, area-Infrastructure, enhancement

#869 Hollowed out public types extending from System.Security.Permissions types
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Permissions/XamlAccessLevel.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Permissions/XamlLoadPermission.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/Permissions/MediaPermission.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/Permissions/WebBrowserPermission.cs
  src/Microsoft.DotNet.Wpf/test/DRT/DrtXaml/DrtXaml/Tests/LoadPermissionTests.cs
Labels: PR

#894 Update to pool-provider sourced machines
  azure-pipelines.yml
Labels: PR

#934 Bindings to System.Dynamic types fail to resolve
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/AssemblyHelper.cs
Labels: PR

#946 Ensure the identity name is the same for C# and VB templates
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json
Labels: PR

#953 Fix for #952 dotnet/wpf builds failing intermittently due to timeouts
  Documentation/testing-in-helix.md
  eng/pipeline.yml
Labels: PR

#958 Change _TestHelixAgentPool from Windows.10.Amd64.Client19H1.Open to Windows.10.Amd64.Client19H1
  eng/pipeline.yml
Labels: PR, auto_merge

#963 test pr
  Documentation/solution-and-project-configurations.md
Labels: auto_merge

#951 Fixing the list of uncommon assemblies used by AssemblyHelper
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/PropertyPathWorker.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/AssemblyHelper.cs
Labels: PR

#975 Change _TestHelixAgentPool from 19H1 to RS5
  azure-pipelines.yml
  eng/pipeline.yml
Labels: PR, auto_merge

#989 Add back support for private C++ frontend
  eng/WpfArcadeSdk/tools/Wpf.Cpp.props
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
  global.json
Labels: PR, auto_merge

#993 Revert "Ensure the identity name is the same for C# and VB templates(#946)"
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json
Labels: PR, auto_merge

#933 making copy-wpf more useful
  Documentation/developer-guide.md
  eng/copy-wpf.ps1
Labels: PR

#979 Incorporate Intellisense XML into ref-assembly nuget packages
  Documentation/intellisense.md
  Microsoft.Dotnet.Wpf.sln
  eng/Versions.props
  eng/WpfArcadeSdk/tools/Packaging.targets
  eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
  global.json
Labels: PR

#1009 Cleanup #if NETFX guarded code and remove XBAP related types
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/cycle-breakers/PresentationFramework/PresentationFramework.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Win32KeyboardDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndKeyboardInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndSource.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/AppSecurityManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/IBrowserCallbackServices.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/IBrowserHostServices.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ResourceContainer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/securitymgrsite.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/IO/Packaging/XamlFilter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Navigation/BindStream.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Utility/SponsorHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/TextBoxBase.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/WebBrowser.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/BrowserInteropHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/DocobjHost.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/DynamicScriptObject.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Navigation/NavigationService.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/StartUpEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/SecurityHelper.cs
Labels: PR

#1024 Fix globbing in ResolveRefApiCompatItems
  eng/WpfArcadeSdk/tools/ApiCompat.targets
Labels: PR, area-Infrastructure, auto_merge, bug

#1025 Fix CommandHandler registration issue identified by DRT failure
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/FlowDocumentReader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/InkCanvas.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextEditor.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextEditorCharacters.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextEditorCopyPaste.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextEditorLists.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextEditorParagraphs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextEditorSelection.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextEditorTables.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextEditorTyping.cs
Labels: PR

#1018 Used nameof instead of magic string
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/clipboard.cs
Labels: PR

#949 Include GAC in changed ref assembly check during WPF build on .NET Framework
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/TaskHelper.cs
Labels: PR

#1028 Dev guide fix
  Documentation/developer-guide.md
Labels: PR

#1027 Add warnings to Microsoft.NET.Sdk.WindowsDesktop to improve UseWpf/UseWinforms and multi-targeting experience
  global.json
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets
Labels: PR

#995 Wrap non-seekable stream in XamlToRtfWriter
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/IO/Packaging/DeobfuscatingStream.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/IO/Packaging/PackWebRequestFactory.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/AppModelKnownContentFactory.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedDocument.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/XamlToRtfWriter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/XpsS0ValidatingLoader.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CompressStream.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/PackUriHelper.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/PackagingExtensions.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/PieceNameHelper.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/streamingZipPartStream.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/CompressionMethodEnum.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/Crc32.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/DeflateOptionEnum.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/IZipIOBlock.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ProgressiveCrcCalculatingStream.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/WriteTimeStream.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipArchive.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipFileInfo.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipFileInfoCollection.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOBlockManager.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOCentralDirectoryBlock.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOCentralDirectoryDigitalSignature.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOCentralDirectoryFileHeader.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOEndOfCentralDirectoryBlock.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOExtraField.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOExtraFieldElement.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOExtraFieldPaddingElement.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOExtraFieldZip64Element.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOFileItemStream.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOLocalFileBlock.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOLocalFileDataDescriptor.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOLocalFileHeader.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOModeEnforcingStream.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIORawDataFileBlock.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOVersionNeededToExtract.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOZip64EndOfCentralDirectoryBlock.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOZip64EndOfCentralDirectoryLocatorBlock.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/WindowsBase.csproj
Labels: PR

#1075 Add one-time installation of a pre-commit git hook to protect generated WPF files
  eng/WpfArcadeSdk/tools/InlineTasks.targets
  eng/WpfArcadeSdk/tools/WPF_Generated_Files.txt
  eng/WpfArcadeSdk/tools/pre-commit.githook
  eng/restore-toolset.ps1
Labels: PR

#1077 Define _WindowsDesktopSdkTargetFrameworkVersionFloor before Microsoft.NET.Sdk.WindowsDesktop.targets is imported
  eng/WpfArcadeSdk/tools/Pbt.props
  eng/WpfArcadeSdk/tools/Pbt.targets
Labels: PR, auto_merge

#1078 Update how timeout is defined in yml files.
  azure-pipelines.yml
  eng/pipeline.yml
Labels: PR, auto_merge

#1080 System.Printing does not consume lib assemblies from WPF GitHub package
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
Labels: PR, bug, hot

#1102 Rebrand master to Preview 8
  eng/Versions.props
Labels: PR

#1087 Port test changes from .NET 4.8
  src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/DrtBaseInput.cs
Labels: PR

#1119 Removing unused source from PresentationFramework
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ApplicationProxyInternal.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/DeploymentExceptionMapper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/IHostService.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/PresentationAppDomainManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/RootBrowserWindow.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/RootBrowserWindowProxy.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/XappLauncher.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/RootBrowserWindowAutomationPeer.cs
Labels: PR, auto_merge, bug
