Repository dotnet/wpf, pull requests merged in 2019-09, with the labels that each got.

#1763 Update Intellisense XML data
  eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
  global.json
Labels: PR, ask-mode, auto_merge

#1780 Rebrand release/3.0 to rc2
  eng/Versions.props
Labels: PR

#1779 Merge release/3.0 into release/3.0-preview9
  eng/Version.Details.xml
  eng/Versions.props
  eng/WpfArcadeSdk/tools/InjectModuleInitializer.targets
  eng/WpfArcadeSdk/tools/Pbt.targets
  eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
  global.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/MatrixCamera.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/OrthographicCamera.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/PerspectiveCamera.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedTextBuilder.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Input/Key.cs
Labels: PR

#1787 Merging missing commits from release/3.0 -> release/3.1
  eng/Version.Details.xml
  eng/Versions.props
  eng/WpfArcadeSdk/tools/InjectModuleInitializer.targets
  eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
  global.json
Labels: PR, tell-mode

#1768 Fixing removal of None from Page under certain conditions
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets
Labels: PR, area-infrastructure, issue-type-bug

#1790 Fixing removal of None from Page under certain conditions
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets
Labels: PR, area-infrastructure, ask-mode, auto_merge, issue-type-bug

#1796 Fixing removal of None from Page under certain conditions (#1790)
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets
Labels: PR, area-infrastructure, issue-type-bug, tell-mode

#1798 Removing vestigial files
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/review.htm
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/ConstrainedDataObject.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/README.md
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/ICommand.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/IBrowserCallbackServices.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Utility/SponsorHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/permissions/UserInitiatedNavigationPermission.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/DocobjHost.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Permissions/InternalPermissions.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CompressStream.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/PieceNameHelper.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/streamingZipPartStream.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/CompressionMethodEnum.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/Crc32.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/DeflateOptionEnum.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/IZipIOBlock.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ProgressiveCrcCalculatingStream.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/WriteTimeStream.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipArchive.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipFileInfo.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipFileInfoCollection.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOBlockManager.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOCentralDirectoryBlock.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOCentralDirectoryDigitalSignature.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOCentralDirectoryFileHeader.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOEndOfCentralDirectoryBlock.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOExtraField.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOExtraFieldElement.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOExtraFieldPaddingElement.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOExtraFieldZip64Element.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOFileItemStream.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOLocalFileBlock.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOLocalFileDataDescriptor.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOLocalFileHeader.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOModeEnforcingStream.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIORawDataFileBlock.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOVersionNeededToExtract.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOZip64EndOfCentralDirectoryBlock.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Zip/ZipIOZip64EndOfCentralDirectoryLocatorBlock.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/Permissions/CompoundFileIOPermission.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/Permissions/RightsManagementPermission.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/Permissions/UserInitiatedRoutedEventPermission.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/Permissions/UserInitiatedRoutedEventPermissionAttribute.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/Permissions/MediaPermission.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/Permissions/WebBrowserPermission.cs
Labels: PR, area-infrastructure

#1895 Ensure that markup compilation is run for all design time builds
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.targets
Labels: PR

#1939 WPF TextBox insertion caret does not render when moved to lower DPI monitor in a PMAv2 process.
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemParameters.cs
Labels: PR, ask-mode

#1929 Cleanup DirectWriteForwarder
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/DirectWriteForwarder.vcxproj
  src/Microsoft.DotNet.Wpf/src/Shared/cpp/Utils.cxx
Labels: PR

#1933 Move System.Xaml.sln into System.Xaml directory
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.sln
Labels: PR

#1934 Remove outdated README files
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/README.md
  src/Microsoft.DotNet.Wpf/src/WindowsBase/README.md
Labels: PR

#1949 WPF TextBox insertion caret does not render when moved to lower DPI monitor in a PMAv2 process
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemParameters.cs
Labels: PR, auto_merge, issue-type-bug

#1951 Update branding for 3.0.1 servicing and turn off stable builds
  eng/Versions.props
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
  packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj
Labels: PR

#912 Fix a incorrect spelled word.
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs
Labels: PR

#1958 Mark ProjectTemplates and Microsoft.NET.Sdk.WindowsDesktop as NonShipping
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
  packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj
Labels: PR

#1959 Mark ProjectTemplates and Microsoft.NET.Sdk.WindowsDesktop as NonShipping
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
  packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj
Labels: PR

#1960 Mark ProjectTemplates and Microsoft.NET.Sdk.WindowsDesktop as NonShipping
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
  packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj
Labels: PR

#1956 Update README.md
  README.md
Labels: PR

#1969 typo: pakage -> package
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsManager.cs
Labels: PR
