Repository dotnet/wpf, pull requests merged in 2019-12, with the labels that each got.

#2252 Improve `HWND` validity testing in `HwndHost`
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/HwndHost.cs
Labels: PR

#2283 Move to 3.1.100 RTM sdk
  global.json
Labels: PR

#2292 Doc was still referring to 3.0 preview 1.
  Documentation/getting-started.md
Labels: PR, auto_merge

#2157 Build orchestration updates
  eng/WpfArcadeSdk/tools/Packaging.targets
  eng/WpfArcadeSdk/tools/SdkReferences.targets
  eng/WpfArcadeSdk/tools/ShippingProjects.props
  eng/WpfArcadeSdk/tools/Wpf.Cpp.props
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
  eng/WpfArcadeSdk/tools/WpfProjectReference.targets
Labels: PR

#2288 Handle incremental build when XAML files are removed from the Page glob
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/IncrementalCompileAnalyzer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/shared.cs
Labels: PR, issue-type-bug

#2303 Import Microsoft.WinFx.props only when it is present
  eng/WpfArcadeSdk/tools/Pbt.props
Labels: PR, auto_merge

#2300 Remove dependency on CorError.h
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/Common.h
Labels: PR

#2301 Add .NET SDK to developer guide
  Documentation/developer-guide.md
Labels: PR

#2305 Remove dependency on .NET SDK installs for IL Tools
  Documentation/developer-guide.md
  eng/Versions.props
  eng/WpfArcadeSdk/tools/InjectModuleInitializer.targets
  eng/WpfArcadeSdk/tools/InjectModuleInitializer/AddModuleConstructorTask.cs
  global.json
Labels: PR
