Repository dotnet/wpf, pull requests merged in 2019-08, with the labels that each got.

#1493 Embed Commit SHA as a string resource in native DLLs
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
Labels: PR, tell-mode

#1502 Removed HandleTwoWayBindingToPropertyWithNonPublicSetter compat flag
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/PropertyPathWorker.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkCompatibilityPreferences.cs
Labels: PR, tell-mode

#1513 XPS: Use original font when subsetting would grow the font
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/TrueTypeSubsetter/truetype.cpp
Labels: PR, area-netfx, area-servicing, issue-type-bug, tell-mode

#1515 Fix for #1198 - fixes potential crashes in high-DPI applications
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/DpiUtil/DpiUtil+DpiAwarenessScope.cs
Labels: PR, tell-mode

#1553 Dev/sambent/speller1540
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/Speller.cs
Labels: PR, area-netfx, area-servicing, issue-type-bug, tell-mode

#1555 Fix double free in calls to CreateTTFDelta(Ex).
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/TrueTypeSubsetter/TtfDelta/ttfdelta.cpp
Labels: PR, area-netfx, area-servicing, issue-type-bug, tell-mode

#1563 Adding PresentationUI to RefAssembly list in build-props.
  eng/WpfArcadeSdk/tools/ApiCompat.props
  eng/WpfArcadeSdk/tools/ShippingProjects.props
Labels: PR, area-infrastructure, ask-mode

#1565 Adopt YAML stages based publishing and validation in dotnet/wpf
  azure-pipelines.yml
  eng/pipeline.yml
Labels: PR, area-infrastructure, tell-mode

#1557 WPF controls in a RowVirtualized DataGrid control lose their value after scrolling
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Selector.cs
Labels: PR

#1578 Remove unsupported TFM's from SupportedTargetFramework.
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
Labels: PR, tell-mode

#1584 remove dnceng ref from TestServices
  src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/TestServices.csproj
Labels: PR, tell-mode

#1606 Update private C++ toolset to 0.0.0.7
  eng/Versions.props
  eng/WpfArcadeSdk/tools/Wpf.Cpp.PrivateTools.targets
  global.json
Labels: PR

#1608 Update roadmap.md
  roadmap.md
Labels: PR

#1633 Re-enable SDL validation build step.
  azure-pipelines.yml
Labels: PR, ask-mode

#1614 fix #1556
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json
Labels: PR, ask-mode

#1665 Updating branding for .NET 5
  eng/Versions.props
Labels: PR, auto_merge

#1674 Update branding for release/3.0 branch
  azure-pipelines.yml
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#1703 making small fixes for sdl violations
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/MatrixCamera.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/OrthographicCamera.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/PerspectiveCamera.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedTextBuilder.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Input/Key.cs
Labels: PR

#1705 Fix issues flagged by Policheck
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/MatrixCamera.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/OrthographicCamera.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/PerspectiveCamera.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedTextBuilder.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Input/Key.cs
Labels: PR, ask-mode, tenet-global-readiness

#1692 Updating issue and feature request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: PR

#1712 Adds missing Version resource to C++ binaries, and fixes PresentationCore.dll's missing Version resource
  eng/WpfArcadeSdk/tools/InjectModuleInitializer.targets
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
Labels: PR, tenet-reliability

#1707 Fixes problems in WindowsDesktop SDK due to _TargetFrameworkVersionWithoutV being undefined sometimes
  eng/WpfArcadeSdk/tools/Pbt.targets
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets
Labels: PR

#1720 Update private C++ tools version to 0.0.0.8
  eng/Versions.props
  global.json
Labels: PR

#1714 Adds missing Version resource to C++ binaries, and fixes PresentationCore.dll's missing Version resource
  eng/WpfArcadeSdk/tools/InjectModuleInitializer.targets
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
Labels: PR, ask-mode, auto_merge, tenet-reliability

#1713 Fixes problems in WindowsDesktop SDK due to _TargetFrameworkVersionWithoutV being undefined sometimes
  eng/WpfArcadeSdk/tools/Pbt.targets
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets
Labels: PR, ask-mode, auto_merge

#1735 Exclude VB Templates from packaging
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
Labels: PR, ask-mode, auto_merge

#1721 Update private C++ tools version to 0.0.0.8 (release/3.0)
  eng/Versions.props
  global.json
Labels: PR, auto_merge, tenet-reliability

#1744 Fix DebuggableAttribute in InjectModuleInitializer post-build targets
  eng/WpfArcadeSdk/tools/InjectModuleInitializer.targets
Labels: PR, area-infrastructure, issue-type-bug, tenet-performance

#1750 Update Versions.props for release/3.1
  azure-pipelines.yml
  eng/Versions.props
Labels: PR

#1745 Fix DebuggableAttribute in InjectModuleInitializer post-build targets
  eng/WpfArcadeSdk/tools/InjectModuleInitializer.targets
Labels: PR, area-infrastructure, ask-mode, tenet-performance
