Repository dotnet/wpf, pull requests merged in 2020-08, with the labels that each got.

#3333 Remove private Cpp tools in favor of using production tools
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/WpfArcadeSdk/tools/Wpf.Cpp.props
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
  eng/common/sdk-task.ps1
  global.json
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/Factory.cpp
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/Factory.h
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/NativePointerWrapper.h
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/Win32/UnsafeNativeMethodsTablet.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/UnsafeNativeMethodsMilCoreApi.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/AssemblyFilter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ContentFilePart.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ResourceContainer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/DataStreams.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Navigation/BindStream.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlTypeMapper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/MS/Internal/Printing/Configuration/UnsafeNativeMethods.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/ReaderWriterLockWrapper.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/NativeMethodsOther.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsOther.cs
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/inc/GDIExporter/precomp.hpp
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/inc/InteropPrinterHandler.hpp
  src/Microsoft.DotNet.Wpf/src/System.Xaml/otherassemblyattrs.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/Misc.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/Condition.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/Misc.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/OtherAssemblyAttrs.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/DispatcherSynchronizationContext.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/ref/WindowsBase.cs
  src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/MS/Win32/UnsafeNativeMethods.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/common/BaseMatrix.cpp
Labels: PR

#3332 adding XamlRuntime msbuild property/metadata
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets
Labels: PR

#2891 Fix raw stylus data to support per-monitor DPI
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/StylusLogic.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerLogic.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerStylusDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/PenContexts.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispLogic.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispStylusDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndTarget.cs
Labels: PR, issue-type-bug

#3329 Remove VerifyWpfDllSet
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/Win32/UnsafeNativeMethodsPenimc.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaContextNotificationWindow.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/Dispatcher.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/WpfDllVerifier.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/WindowsBase.csproj
Labels: PR, hot

#3372 Add CPD strict dependencies for dotnet/installer
  eng/Version.Details.xml
Labels: PR

#3406 Fix RuntimeFrameworkReferences for RTM builds
  eng/Version.Details.xml
  eng/Versions.props
  eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.props
  eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.targets
Labels: PR

#3407 Merge from release/5.0
  eng/Version.Details.xml
Labels: PR
