Repository dotnet/wpf, pull requests merged in 2020-01, with the labels that each got.

#2366 Ensure the WindowsDesktopSdk RepoLocation overrides all others.
  eng/WpfArcadeSdk/tools/ShippingProjects.props
Labels: PR, area-infrastructure, auto_merge

#2427 Fixing Microsoft Security Advisory CVE-2020-0605 : .NET Core Remote Code Execution Vulnerability
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/StickyNote/StickyNoteContentControl.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextRange.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsDocument.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/ReachFramework.csproj
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Markup/XamlReaderProxy.cs
Labels: PR

#2430 Microsoft Security Advisory CVE-2020-0606 : .NET Core Remote Code Execution Vulnerability (5.0 PR)
  src/Microsoft.DotNet.Wpf/cycle-breakers/PresentationFramework/PresentationFramework.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/StickyNote/StickyNoteContentControl.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextRange.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlReader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsDocument.cs
Labels: PR

#2271 TreeView scroll hang
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ItemsControl.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
Labels: PR, Servicing-consider, auto_merge, netfx-servicing-approved

#2270 SharedSizeGroup loop
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DefinitionBase.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Grid.cs
Labels: PR, Servicing-consider, auto_merge, netfx-servicing-approved

#2269 Ribbon focus war
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonHelper.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonMenuButton.cs
Labels: PR, Servicing-consider, auto_merge, netfx-servicing-approved

#2282 Fix STATUS_ILLEGAL_INSTRUCTION crash in win-x86 on some Xeon CPU's
  eng/Versions.props
  eng/WpfArcadeSdk/tools/Wpf.Cpp.props
  global.json
Labels: PR, Servicing-approved, auto_merge

#2436 Update branding from '4.8.1-rtm' to '4.8.1-servicing'
  eng/Versions.props
Labels: PR

#2438 [release/3.1] Update branding for non 4.8.1 packages
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
  packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj
Labels: PR, auto_merge

#2437 [release/3.0] Update non 4.8.0 package branding
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
  packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj
Labels: PR, auto_merge

#2440 [release/3.0] Centralize VersionPrefix information in Version.props
  eng/Versions.props
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
  packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj
Labels: PR, tell-mode

#2439 [release/3.1] Centralize VersionPrefix information in Version.props
  eng/Versions.props
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
  packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj
Labels: PR, tell-mode

#2449 Add S.W.Forms.Primitives references to accommodate type-moves coming from dotnet/winforms
  src/Microsoft.DotNet.Wpf/src/PresentationUI/PresentationUI.csproj
  src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/WindowsFormsIntegration.csproj
  src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/ref/WindowsFormsIntegration-ref.csproj
Labels: PR, auto_merge
