Repository dotnet/wpf, pull requests merged in 2020-02, with the labels that each got.

#2498 Branding updates
  eng/Versions.props
Labels: PR, auto_merge

#2507 Build orchestration fixups
  eng/WpfArcadeSdk/tools/InlineTasks.targets
  eng/WpfArcadeSdk/tools/Wpf.Cpp.props
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
  eng/WpfArcadeSdk/tools/WpfProjectReference.targets
Labels: PR, auto_merge

#2521 Add support for publishing Debug packages separately
  Microsoft.Dotnet.Wpf.sln
  Microsoft.Dotnet.Wpf.sln.bak
  eng/WpfArcadeSdk/tools/Packaging.props
  eng/WpfArcadeSdk/tools/SdkReferences.targets
  eng/WpfArcadeSdk/tools/TestProjects.targets
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
  eng/WpfArcadeSdk/tools/WpfProjectReference.targets
  eng/configure-toolset.ps1
  eng/pipeline.yml
  packaging/Microsoft.DotNet.Arcade.Wpf.Sdk/Microsoft.DotNet.Arcade.Wpf.Sdk.ArchNeutral.csproj
  packaging/Microsoft.DotNet.Wpf.GitHub/Microsoft.DotNet.Wpf.GitHub.ArchNeutral.csproj
  packaging/Microsoft.DotNet.Wpf.GitHub/Microsoft.DotNet.Wpf.GitHub.csproj
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
  packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj
Labels: PR

#2522 Enable publishing in Debug builds
  eng/pipeline.yml
Labels: PR, auto_merge

#2523 Set _SignType=real for Debug builds
  eng/pipeline.yml
Labels: PR

#2524 Add $(Configuration) to AssetManifest file name
  eng/WpfArcadeSdk/Sdk/Sdk.props
  eng/WpfArcadeSdk/tools/Publishing.props
  eng/WpfArcadeSdk/tools/Publishing.targets
Labels: PR

#2525 Make ArtifactsTmpDir platform-specific
  eng/WpfArcadeSdk/tools/FolderPaths.props
  eng/WpfArcadeSdk/tools/Publishing.props
Labels: PR, auto_merge

#2529 Publishing fixup for .Debug builds
  eng/Publishing.props
  eng/WpfArcadeSdk/tools/FolderPaths.props
Labels: PR

#2531 Move DebugInformationFormat setting to Wpf.Cpp.target
  eng/Publishing.props
  eng/WpfArcadeSdk/tools/Wpf.Cpp.props
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
Labels: PR

#2534 Set debug optimization flags early in build
  eng/WpfArcadeSdk/tools/Wpf.Cpp.props
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
Labels: PR

#2547 Ensure C/C++ .lib builds in dotnet-wpf-int will set DebugInformationFormat=oldStyle
  eng/WpfArcadeSdk/tools/FolderPaths.targets
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
Labels: PR, auto_merge

#2562 Fixup dependencies
  eng/Version.Details.xml
Labels: PR

#2572 Branding updates for 3.1.3
  eng/Versions.props
Labels: PR, auto_merge

#2487 [release/3.1] Unescape PresentationBuildTasks.dll paths containing special characters
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.props
Labels: PR, Servicing-approved, auto_merge

#2573 Update win10 sdk used by WPF builds to 18362
  eng/WpfArcadeSdk/tools/Wpf.Cpp.props
  src/Microsoft.DotNet.Wpf/src/WpfGfx/common/DirectXLayer/XMath/matrix_xm.hpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/common/DirectXLayer/XMath/quaternion_xm.hpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/common/DirectXLayer/XMath/vector3_xm.hpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/common/DirectXLayer/XMath/vector4_xm.hpp
Labels: PR

#2606 Update branding to preview2
  eng/Versions.props
Labels: PR

#2605 Include additional headers in the transported Microsoft.DotNet.Arcade.Wpf.Sdk used by internal dotnet-wpf-int repo
  eng/WpfArcadeSdk/tools/FolderPaths.targets
  packaging/Microsoft.DotNet.Arcade.Wpf.Sdk/Microsoft.DotNet.Arcade.Wpf.Sdk.ArchNeutral.csproj
Labels: PR

#2619 [release/5.0-preview1] Update CI and PR triggers
  azure-pipelines.yml
Labels: PR

#2621 [release/5.0-preview1] Update CI and PR branches
  azure-pipelines.yml
Labels: PR

#2463 Contributing: fixed some typos
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/CompilationUnit.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/Win32/UnsafeNativeMethodsPointer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/CommandDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/FocusChangedEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputReport.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/KeyEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/KeyboardEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/KeyboardInputProviderAcquireFocusEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseButtonEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseWheelEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/QueryCursorEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/RawAppCommandInputReport.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/RawKeyboardInputReport.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/RawMouseInputReport.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/RawTextInputReport.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/RawUIStateInputReport.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/RawStylusInputReport.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/TouchPoint.cs
Labels: PR

#2633 Create security.md
  SECURITY.md
Labels: PR

#2660 Merge 3.1 to master
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.props
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DefinitionBase.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Grid.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ItemsControl.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonHelper.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonMenuButton.cs
Labels: PR

#2661 Merge release/3.1 to release/5.0-preview1 via master
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.props
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DefinitionBase.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Grid.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ItemsControl.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonHelper.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonMenuButton.cs
Labels: PR

#2667 Fixup Environment.UserInteractive uses to workaround https://github.com/dotnet/runtime/issues/32929
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaContext.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/CommonDialog.cs
Labels: PR

#2675 Fixup microsoft.netcore.app dependencies
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/WpfArcadeSdk/tools/CreateTestPayload.targets
  eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.props
  eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.targets
  eng/helixpublish.proj
  global.json
Labels: PR
