Repository dotnet/wpf, pull requests merged in 2021-10, with the labels that each got.

#5431 Switch to 1ES R&D pools on main
  azure-pipelines.yml
  eng/pipeline.yml
Labels: PR

#5449 Update branding for 3.1.21
  eng/Versions.props
Labels: PR

#5450 Update branding for 5.0.12
  eng/Versions.props
Labels: PR

#5453 [release/6.0] Overbuild caused by PackageReference support (Remove WPF Arcade workaround)
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs
Labels: PR, Servicing-approved

#5495 Merging internal commits for release/5.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#5426 WPF projects that use a versioned custom SDK fail to build
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs
Labels: PR, Queue for test pass
