Repository dotnet/wpf, pull requests merged in 2021-08, with the labels that each got.

#4977 Update branding for 5.0.10
  eng/Versions.props
Labels: PR

#4976 Update branding for 3.1.19
  eng/Versions.props
Labels: PR

#4998 Auto-trigger on internal/release/6* commits
  azure-pipelines.yml
Labels: PR

#5004 System.Windows.Markup.XamlParseException when reading resource file
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ContentFilePart.cs
Labels: PR

#4958 [release/5.0] Fixing deterministic build bug in WPF's BAML files
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XmlnsCache.cs
Labels: PR, Servicing-approved

#4939 [release/5.0] Use reflection-only context for InternalsVisibleToAttribute type comparison
  src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/ReflectionHelper.cs
Labels: PR, Servicing-approved

#5052 Merging internal commits for release/3.1
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#5051 Merging internal commits for release/5.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#5059 [release/3.1] ILDasm build break
  eng/WpfArcadeSdk/tools/InjectModuleInitializer.targets
Labels: PR

#5005 [release/3.1] Do not reflow lines after measure
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TextBlock.cs
Labels: PR, Servicing-consider

#5007 [release/3.1] Port HostVisual fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/HostVisual.cs
Labels: PR, Servicing-consider

#5008 [release/3.1] Port VSP Freeze fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/HierarchicalVirtualizationConstraints.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
Labels: PR, Servicing-consider

#5013 [release/3.1] Port ToolTip reentrancy fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs
Labels: PR, Servicing-consider

#5014 [release/3.1] DataGrid.Copy: fail silently if clipboard is locked
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGrid.cs
Labels: PR, Servicing-consider

#5015 [release/3.1] Port HwndHost stack trace fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/HwndHost.cs
Labels: PR, Servicing-consider

#5016 [release/3.1] Port FixedPage SOM fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedSOMPageConstructor.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedTextBuilder.cs
Labels: PR, Servicing-consider

#5017 [release/3.1] Port nulll ItemAutomationPeer fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/DataGridColumnHeadersPresenterAutomationPeer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/GroupItemAutomationPeer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ItemsControlAutomationPeer.cs
Labels: PR, Servicing-consider

#5018 [release/3.1] Port predefined package fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs
Labels: PR, Servicing-consider

#5023 [release/3.1] Port WindowChrome fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndMouseInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Shell/WindowChromeWorker.cs
Labels: PR, Servicing-consider

#5024 [release/3.1] Port stylus shutdown fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndSource.cs
Labels: PR, Servicing-consider

#5028 [release/3.1] Port IME reentrancy fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkCompatibilityPreferences.cs
Labels: PR, Servicing-consider

#5033 [release/3.1] Port UpdatePeer fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ItemAutomationPeer.cs
Labels: PR, Servicing-consider

#5020 [release/3.1] Port VSP floating-point hang from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
Labels: PR, Servicing-consider

#5029 [release/3.1] Web browser completion events 3.1
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/WebBrowserEvent.cs
Labels: PR, Servicing-consider

#5032 [release/3.1] Port nested ScrollIntoView fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ScrollViewer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
Labels: PR, Servicing-consider

#5019 [release/5.0] port speller perf fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/MsSpellCheckLib/SpellChecker/SpellChecker.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/MsSpellCheckLib/Utils/Extensions.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/WinRTSpellerInteropExtensions.cs
Labels: PR, Servicing-consider

#5021 [release/5.0] Port fix for VSP floating-point hang from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
Labels: PR, Servicing-consider

#5022 [release/5.0] Port WindowChrome fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndMouseInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Shell/WindowChromeWorker.cs
Labels: PR, Servicing-consider

#5026 [release/5.0] Port stylus shutdown fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndSource.cs
Labels: PR, Servicing-consider

#5027 [release/5.0] Port IME reentrancy fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkCompatibilityPreferences.cs
Labels: PR, Servicing-consider

#5030 [release/5.0] Web browser completion events 5.0
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/WebBrowserEvent.cs
Labels: PR, Servicing-consider

#5031 [release/5.0] Port nested ScrollIntoView fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ScrollViewer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
Labels: PR, Servicing-consider

#5034 [release/5.0] Port UpdatePeer fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ItemAutomationPeer.cs
Labels: PR, Servicing-consider

#5003 Fixing bug of searching for heading level throwing exception
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/Schema.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/HeadingLevel.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/PropertyCondition.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/UIAutomationClient.csproj
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/ref/UIAutomationClient.cs
Labels: PR

#4717 Avoid new delegate allocation on each DispatcherTimer tick
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/DispatcherTimer.cs
Labels: PR

#4722 Avoid unnecessary boxing in calls to EasyTraceEvent
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/Trace.cs
Labels: PR

#4724 Avoid boxing in FrugalList
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/FrugalList.cs
Labels: PR

#4731 Use Dictionary instead of Hashtable in EventMap
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Automation/EventMap.cs
Labels: PR

#4732 Avoid unnecessary DispatcherOperationCallback allocations in ElementProxy properties
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Automation/ElementProxy.cs
Labels: PR

#4733 Remove delegate allocations from FindAmbientValues
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/ObjectWriterContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/XamlContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/ArrayHelper.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlTypeName.cs
Labels: PR

#4736 Avoid calling GetInvocationList on hot paths
  src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/EventHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndSource.cs
Labels: PR

#4754 Avoid POINT allocations
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndMouseInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndStylusInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndTarget.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/ActiveXSite.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/webbrowsersite.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/ImmComposition.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/PointUtil.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/NativeMethodsCLR.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/NativeMethodsSetLastError.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/SafeNativeMethodsCLR.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsCLR.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsTextServices.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/HwndProxyElementProvider.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Win32/UnsafeNativeMethods.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Win32/UnsafeNativeMethods.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/SplashScreen.cs
  src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/DrtBase.cs
  src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/MS/Internal/PointUtil.cs
  src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/MS/Win32/NativeMethodsCLR.cs
  src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/MS/Win32/SafeNativeMethodsCLR.cs
  src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/MS/Win32/UnsafeNativeMethodsCLR.cs
Labels: PR

#4755 Stop allocating two RawMouseActions[] arrays in PreNotifyInput
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseDevice.cs
Labels: PR

#4757 Remove more unnecessary DispatcherOperationCallbacks instances
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/TouchDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndMouseInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/HostVisual.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Frame.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/NGCSerializationManagerAsync.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/XpsOMSerializationManagerAsync.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/XpsSerializationManagerAsync.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonGalleryItem.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/SplashScreen.cs
Labels: PR

#4975 port speller perf fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/MsSpellCheckLib/SpellChecker/SpellChecker.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/MsSpellCheckLib/Utils/Extensions.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/WinRTSpellerInteropExtensions.cs
Labels: PR

#4979 Port fix for VSP floating-point hang from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
Labels: PR

#4985 Port IME reentrancy fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkCompatibilityPreferences.cs
Labels: PR

#4993 Port WebBrowser completion events fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/WebBrowserEvent.cs
Labels: PR

#4994 Port nested ScrollIntoView fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ScrollViewer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
Labels: PR

#4995 Port UpdatePeer fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ItemAutomationPeer.cs
Labels: PR

#5065 Update the testing api changes in developer-guide.md
  Documentation/developer-guide.md
Labels: PR

#4756 Remove delegate/array allocations from EventMap.NotifySources
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Automation/EventMap.cs
Labels: PR

#4981 Port WindowChrome fix from 4.8
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndMouseInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Shell/WindowChromeWorker.cs
Labels: PR

#5088 Update the SDK version and disable module initializer warning
  global.json
  src/Microsoft.DotNet.Wpf/src/PresentationCore/ModuleInitializer.cs
Labels: PR

#4327 Loc updates
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.zh-Hans.xlf
Labels: PR

#4407 Fix scrollbar zh-Hans localization
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.zh-Hans.xlf
Labels: PR

#5084 Update WindowsDesktop SDK to support recent changes to implicit global usings feature
  Directory.Build.props
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.WPF.props
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.WPF.targets
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets
Labels: PR

#4968 Remove Obsolete APIs
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/Factory.cpp
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/Factory.h
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/NativePointerWrapper.h
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/Win32/UnsafeNativeMethodsTablet.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/UnsafeNativeMethodsMilCoreApi.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/AssemblyFilter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ResourceContainer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlTypeMapper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/MS/Internal/Printing/Configuration/UnsafeNativeMethods.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintConfig/FallbackPTProvider.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/ReaderWriterLockWrapper.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/NativeMethodsOther.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsOther.cs
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/inc/GDIExporter/precomp.hpp
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/Misc.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/Condition.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/Misc.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/DispatcherSynchronizationContext.cs
  src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/MS/Win32/UnsafeNativeMethods.cs
Labels: PR

#5105 Update release/6.0 branding to rc2
  eng/Versions.props
Labels: PR

#5095 Update main branding to .NET 7.0 alpha 1
  eng/Versions.props
  eng/WpfArcadeSdk/Sdk/Sdk.props
Labels: PR

#5107 Add net7 and net7 transport nuget feeds to nuget.config
  NuGet.config
Labels: PR

#5111 Update runtime package name to fix coherency
  eng/Version.Details.xml
Labels: PR

#5130 [release/6.0-rc1] Accessibility: Fix ClickablePoint property when IsOffscreen is true
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Automation/Peers/AutomationPeer.cs
Labels: PR

#5126 Fix ClickablePoint property when IsOffscreen is true.
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Automation/Peers/AutomationPeer.cs
Labels: PR

#5225 Respond to PR feedback
  Directory.Build.targets
Labels: PR
