Repository dotnet/wpf, pull requests merged in 2021-02, with the labels that each got.

#4133 Add initial pull request template to WPF repo
  PULL_REQUEST_TEMPLATE
Labels: PR

#4135 Add 'Untriaged' label to WPF GitHub PR template
  PULL_REQUEST_TEMPLATE
Labels: PR

#4148 Fix comment typo in DragDrop.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/DragDrop.cs
Labels: PR

#4017 Use readonly struct in System.Windows.Input.Manipulations.PointF
  src/Microsoft.DotNet.Wpf/src/System.Windows.Input.Manipulations/System/Windows/Input/Manipulations/ManipulationSequence.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Input.Manipulations/System/Windows/Input/Manipulations/PointF.cs
Labels: Included in test pass, PR

#3998 Use char overload in System.Xaml
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/DateTimeValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/KnownStrings.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/MeScanner.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/XamlName.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/ClrNamespaceUriParser.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlMarkupExtensionWriter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlType.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlTypeName.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlXmlWriter.cs
Labels: Included in test pass, PR

#3117 Remove custom copy of PtrToStringChars
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/Common.h
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/Factory.cpp
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontCollection.cpp
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/LocalizedStrings.cpp
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/TrueTypeSubsetter/util2.cpp
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/TrueTypeSubsetter/util2.h
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/wpfvcclr.h
Labels: Included in test pass, PR, Priority:1

#2843 Using array empty to replace create an empty array
  eng/WpfArcadeSdk/tools/CodeGen/AvTrace/AvTraceMessages.tt
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Generated/AvTraceMessages.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Annotations/Serializer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Generated/AvTraceMessages.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006Reader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006SchemaContext.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/ControlType.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/Generated/AvTraceMessages.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/Compoundfile/DataSpaceManager.cs
Labels: Included in test pass, PR, Priority:2

#4151 Remove method with the same signature created in two different CTP PRs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/KnownStrings.cs
Labels: PR

#4163 Update release/5.0 branding to 5.0.4
  eng/Versions.props
Labels: PR

#4165 Merge internal/release/3.1 and update branding in release/3.1 to 3.1.13
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#4170 Revert "Merge internal/release/3.1 and update branding in release/3.1 to 3.1.13"
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#4171 Merge internal/release/3.1 and update branding in release/3.1 to 3.1.13
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#4175 Updated developer guide TFM to 6.0
  Documentation/developer-guide.md
Labels: PR

#3437 [release/5.0] Fix raw stylus data to support per-monitor DPI
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/StylusLogic.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerLogic.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerStylusDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/PenContexts.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispLogic.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispStylusDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndTarget.cs
Labels: PR, Servicing-approved

#4192 Use reflection-only context for InternalsVisibleToAttribute type comparison
  src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/ReflectionHelper.cs
Labels: PR

#4206 WPF fails to pass on embedinteroptypes metadata to items in its temp project
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs
Labels: PR

#4210 Update .NET 6.0 branding to Preview 3
  eng/Versions.props
Labels: PR

#4225 Update release/3.1 branding to 3.1.14
  eng/Versions.props
Labels: PR

#4224 Update release/5.0 branding to 5.0.5
  eng/Versions.props
Labels: PR
