Repository dotnet/wpf, pull requests merged in 2021-03, with the labels that each got.

#4261 [release/5.0] Remove legacy RestoreSources
  eng/Versions.props
Labels: PR

#4274 [release/3.1] Merge internal commits
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#4275 [release/5.0] Merge internal commits
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#4282 Fix comment typo in MarkupCompilePass2.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass2.cs
Labels: PR

#4289 Change WPF's default branch to 'main': Update pipeline triggers to include 'main'
  azure-pipelines.yml
Labels: PR

#4290 Temporarily disable PR builds in main to prevent PR builds for all open PRs from running
  azure-pipelines.yml
Labels: PR

#4291 Enable build triggers after default branch rename from master to main
  azure-pipelines.yml
Labels: PR

#4298 Remove unused namespace System.Drawing.Printing causing build breaks in recent deps updates
  src/Microsoft.DotNet.Wpf/src/ReachFramework/AlphaFlattener/metrodevice.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/MS/Internal/Printing/Configuration/SafeWinSpoolPrinterHandle.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/MS/Internal/Printing/Configuration/UnsafeNativeMethods.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/MS/Internal/Printing/Configuration/WinSpoolPrinterCapabilities.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintConfig/FallbackPTProvider.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintConfig/PTConverter.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintConfig/PTProvider.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintConfig/PTProviderBase.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/NGCSerializationManager.cs
Labels: PR

#4205 Fix publishing in VS when runtime identifier in publishing profile differs from project rid
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs
Labels: PR, WindowsDesktop SDK

#4318 Update WPF public repo .NET 6.0 branding to preview 4
  eng/Versions.props
Labels: PR

#4323 Enable pull request and CI builds for 6.0 branches
  azure-pipelines.yml
Labels: PR

#4331 Migrate to OneLocBuild
  eng/pipeline.yml
Labels: PR

#4177 Replaced some Dictionaries and Hashtables with Hashsets
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FontResourceCache.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Resources/ContentFileHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Automation/Peers/AutomationPeer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/Primitives/RibbonMenuItemsPanel.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/ObjectWriterContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/XamlParserContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/XmlNsInfo.cs
Labels: Included in test pass, PR, Performance

#2574 Use theme to create DocumentGridPage borders
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/DocumentGridPage.cs
  src/Microsoft.DotNet.Wpf/src/Themes/Generator/ThemeGenerator.proj
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Aero/themes/Aero.NormalColor.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Aero2/Themes/Aero2.NormalColor.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.AeroLite/Themes/AeroLite.NormalColor.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Classic/Themes/Classic.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Luna/Themes/Luna.HomeStead.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Luna/Themes/Luna.Metallic.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Luna/Themes/Luna.NormalColor.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Royale/Themes/Royale.NormalColor.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/XAML/DocumentViewer.xaml
Labels: Included in test pass, PR
