Repository dotnet/wpf, pull requests merged in 2021-01, with the labels that each got.

#3926 Fix a wrong property name in a comment
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
Labels: PR

#3923 Add clearer win32 exception information in SplashScreen CreateWindow
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/SplashScreen.cs
Labels: PR

#3909 Fix Grid SetFinalSize method comment
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Grid.cs
Labels: PR

#3851 Use Array.Empty instead of creating list in ResourceDictionaryDiagnostics
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Diagnostics/ResourceDictionaryDiagnostics.cs
Labels: PR

#2965 Remove backup file for solution
  Microsoft.Dotnet.Wpf.sln.bak
Labels: PR

#939 Set the lock object as readonly
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispLogic.cs
Labels: PR

#3951 Move remaining release/5.0 change to master: [release/5.0] Support source generators in WPF projects (#3846) [5.0.2 servicing]
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs
Labels: PR

#3493 added label "ResourceKey" to trace details when resource is not found
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Generated/AvTraceMessages.cs
Labels: PR

#3318 Call SHA1.HashData static helper instead of instantiating SHA1CSP
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/WindowsRuntime/Generated/WinRT/GuidGenerator.cs
Labels: PR

#3085 Reduce memory usage by Array.Empty
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ValueSerializer.cs
Labels: PR

#3009 Remove always-true condition
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Input/KeyConverter.cs
Labels: PR

#3969 Update documentation links to .NET SDK
  README.md
Labels: PR

#3970 Update Visual Studio link in readme to VS Preview
  README.md
Labels: PR

#3976 Adjust project templates to support .NET 6.0 (and default to it)
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/.template.config/template.json
Labels: PR

#3907 Make CustomGuids as readonly
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/InkSerializedFormat/GuidTagList.cs
Labels: Included in test pass, PR

#3908 Using readonly struct in WPF Ink module
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/ContourSegment.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/EllipticalNodeOperations.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/Quad.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/StrokeFIndices.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/StrokeNode.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/StrokeNodeData.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/StrokeNodeOperations.cs
Labels: Included in test pass, PR

#3086 Special the capacity to improve performance
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/NameScope.cs
Labels: Included in test pass, PR

#3279 Use the new Marshal.IsTypeVisibleFromCom Api
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MarshalLocal.cs
Labels: Included in test pass, PR

#2976 Don't double import WinFX targets
  packaging/Microsoft.NET.Sdk.WindowsDesktop/Sdk/Sdk.props
  packaging/Microsoft.NET.Sdk.WindowsDesktop/Sdk/Sdk.targets
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
  packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
Labels: Included in test pass, PR

#3932 Replace the Dictionary with HashSet in AppDomainShutdownMonitor
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/D3DImage.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/AppDomainShutdownMonitor.cs
Labels: Included in test pass, PR

#3991 Merge internal/release/5.0 to release/5.0 and update branding
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/post-build/publish-using-darc.ps1
  eng/pipeline.yml
Labels: PR

#3995 Merge internal/release/3.1 in to release/3.1 and update branding to 3.1.11
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#4009 [release/5.0] Improve handling of custom paths in markup compiler
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/PathInternal.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/CompilerWrapper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/TaskHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass1.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass2.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj
Labels: PR, Servicing-approved

#4010 Remove unused local variable 'selfStyle' and related conditionals in System.Windows.StyleHelper.GetThemeStyle
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/StyleHelper.cs
Labels: PR

#4004 Fix Style.cs comment
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Style.cs
Labels: PR

#3084 Fix unknown character
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/ExceptionStringTable.txt
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/Strings.resx
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.cs.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.de.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.es.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.fr.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.it.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.ja.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.ko.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.pl.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.pt-BR.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.ru.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.tr.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.zh-Hans.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.zh-Hant.xlf
Labels: PR

#4038 Port release/5.0 5.0.3 servicing fix to master: markup compiler updates
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/CompilerWrapper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/TaskHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass1.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass2.cs
Labels: PR

#4046 WPF ARM64: Update Wpf.Cpp.Targets TFM. win10- should be win-.
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
Labels: PR

#4048 WPF support for ARM64: Enable build in public repo and update packaging
  Directory.Build.props
  eng/WpfArcadeSdk/tools/ApiCompat.targets
  eng/copy-wpf.ps1
  eng/helixpublish.proj
  eng/pipeline.yml
  packaging/Microsoft.DotNet.Arcade.Wpf.Sdk/Microsoft.DotNet.Arcade.Wpf.Sdk.ArchNeutral.csproj
  packaging/Microsoft.DotNet.Wpf.GitHub/Microsoft.DotNet.Wpf.GitHub.ArchNeutral.csproj
  packaging/Microsoft.DotNet.Wpf.GitHub/Microsoft.DotNet.Wpf.GitHub.csproj
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
  packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj
Labels: PR

#4083 Update branding to preview2 after release/6.0-preview1 branch
  eng/Versions.props
Labels: PR

#4089 Make source generator and package reference support opt-out (on by default)
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
Labels: PR

#4071 Fix DataObject.cs comment
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs
Labels: PR

#4072 Fix comment typo in DataObjectCopyingEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/DataObjectCopyingEventArgs.cs
Labels: PR

#4070 Remove unused local variable 'xamlType' in MS.Internal.Xaml.Parser.MePullParser
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/MePullParser.cs
Labels: PR

#4069 Merge Dictionary.TryGetValue and Dictionary.Remove to Dictionary.Remove in NameFixupGraph
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/NameFixupGraph.cs
Labels: PR

#4053 Fix incremental build for WPF projects with dotnet.exe
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/CompilerState.cs
Labels: PR

#4098 [release/5.0] Fix incremental build issue in WPF's markup compiler
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/CompilerState.cs
Labels: PR, Servicing-approved

#4099 [release/3.1] Fix major incremental build issue in WPF's markup compiler
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/CompilerState.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj
Labels: PR, Servicing-approved
