Repository dotnet/wpf, pull requests merged in 2022-05, with the labels that each got.

#6513 Set up new wpf pipeline
  azure-pipelines1.yml
Labels: PR

#6521 Update branding to 6.0.6
  eng/Versions.props
Labels: PR

#6520 Update branding to 3.1.26
  eng/Versions.props
Labels: PR

#6536 temporarily disable pieline for PRs
  azure-pipelines1.yml
Labels: PR

#6537 Update azure-pipelines1.yml for experimentation
  azure-pipelines1.yml
Labels: PR

#6265 Avoid unnecessary enumerator allocations in XamlDirective.GetHashCode
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlDirective.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlLanguage.cs
Labels: PR, Queue for test pass

#6269 Avoid exceptional string allocation in StaticExtension.ProvideValue
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/StaticExtension.cs
Labels: PR, Queue for test pass

#6270 Don't allocate fallback name in XamlNamespace.GetXamlType unless it's needed
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlNamespace.cs
Labels: PR, Queue for test pass

#6279 Avoid boxing list enumerator in XamlObjectWriter.Logic_ConvertPositionalParamsToArgs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriter.cs
Labels: PR, Queue for test pass

#6281 Avoid boxing list/array enumerator in CreateTextLSRuns
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/TextFormatting/TextStore.cs
Labels: PR, Queue for test pass

#6282 Avoid enumerator boxing in XamlSchemaContext.UpdateNamespaceByUriList
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlSchemaContext.cs
Labels: PR, Queue for test pass

#6309 Stop boxing in Visual.SetDpiScaleVisualFlags
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/DpiScale.cs
Labels: PR, Queue for test pass

#6268 Remove unnecessary string and string[] allocations from MS.Internal.ContentType
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/ContentType.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/WindowsBase.csproj
Labels: PR, Queue for test pass

#6539 update intellisense version
  eng/Versions.props
Labels: PR

#6496 Don't include d3dcompiler_47.dll on ARM64.
  Microsoft.Dotnet.Wpf.sln
  src/Microsoft.DotNet.Wpf/redist/D3DCompiler/D3DCompiler.vcxproj
Labels: PR, Servicing-approved

#5925 Remove the unnecessary calculate code in ImageSource.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/ImageSource.cs
Labels: PR, Included in test pass, Queue for test pass

#5954 Explicit delegate types
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/UnsafeNativeMethodsMilCoreApi.cs
Labels: PR, Included in test pass, Queue for test pass

#6053 Replace resource constants with properties in WindowsFormsIntegration
  eng/WpfArcadeSdk/tools/SystemResources.props
  src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/SR.cs
  src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/System/Windows/Integration/IntegrationExceptionEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/System/Windows/Integration/PropertyMap.cs
  src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/System/Windows/Integration/PropertyMappingExceptionEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/System/Windows/Integration/WindowsFormsHost.cs
  src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/WindowsFormsIntegration.csproj
Labels: PR, Included in test pass, Queue for test pass

#6130 Remove unused files
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/dir.props
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/dir.props
  src/Microsoft.DotNet.Wpf/src/PresentationUI/dir.props
  src/Microsoft.DotNet.Wpf/src/ReachFramework/dir.props
  src/Microsoft.DotNet.Wpf/src/System.Printing/dir.props
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Themes/Generator/ThemeGenerator.proj
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/dir.props
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/dir.props
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationProvider/dir.props
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/dir.props
  src/Microsoft.DotNet.Wpf/src/WindowsBase/dir.props
  src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/dir.props
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/makefile
  src/Microsoft.DotNet.Wpf/src/WpfGfx/common.inc
  src/Microsoft.DotNet.Wpf/src/WpfGfx/common/dirs.proj.bak
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/fxjit/dir.props
  src/Microsoft.DotNet.Wpf/src/WpfGfx/exts/makefile
  src/Microsoft.DotNet.Wpf/src/WpfGfx/shared/dir.props
  src/Microsoft.DotNet.Wpf/src/WpfGfx/shared/dir.targets
  src/Microsoft.DotNet.Wpf/src/WpfGfx/shared/shared.props
  src/Microsoft.DotNet.Wpf/test/DRT/DrtXaml/dir.props
  src/Microsoft.DotNet.Wpf/test/DRT/dir.props
  src/Microsoft.DotNet.Wpf/test/MultiTargeting.props
Labels: PR, Included in test pass, Queue for test pass

#6245 Fix setting DPI awareness
  src/Microsoft.DotNet.Wpf/src/PresentationCore/ModuleInitializer.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#6266 Disable Indeterminate animation when hiding ProgressBar
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ProgressBar.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#6345 Account for optional out parameters in IStream
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/api/exports.cpp
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#6333 Replace resource constants with properties in System.Xaml
  eng/WpfArcadeSdk/tools/SystemResources.props
  src/Microsoft.DotNet.Wpf/src/System.Xaml/SR.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ArrayExtension.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/StaticExtension.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/StaticExtensionConverter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/TypeExtension.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/TypeExtensionConverter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/NameScope.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/AttachablePropertyServices.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/NameFixupGraph.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/ObjectWriterContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/ServiceProviderContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/XamlContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/DeferredWriter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/XmlNsInfo.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/NameReferenceConverter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/NameScopeDictionary.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/GenericTypeNameParser.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/MePullParser.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/MeScanner.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/XamlPullParser.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/XamlScanner.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Primitives/WriterDelegate.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Primitives/XamlBackgroundReader.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Primitives/XamlNodeList.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Replacements/Reference.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Runtime/ClrObjectRuntime.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Runtime/DynamicMethodRuntime.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/ClrAttachableProperty.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/ClrEvent.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/ClrProperty.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/CollectionReflector.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/DirectiveProperty.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/ImplicitProperty.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/Reflector.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/TypeReflector.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/UnknownProperty.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlDirective.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlMemberInvoker.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlTypeInvoker.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlValueConverter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XaslMember.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XaslMemberReference.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XaslNamespace.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XmlNamespace.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlException.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlMarkupExtensionWriter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlMember.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlObjectReader.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlSchemaContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlServices.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlType.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlTypeName.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlWriter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlXmlWriter.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#6555 [Port .NET 6 ] Fixes rounding error while glyphrun serialization
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/GlyphsSerializer.cs
Labels: PR, Servicing-approved

#6295 Fixes rounding error while glyphrun serialization
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/GlyphsSerializer.cs
Labels: PR, Servicing-approved

#6566 Merging internal commits for release/3.1
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#6565 Merging internal commits for release/5.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#6616 Update branding to prerelease 6
  eng/Versions.props
Labels: PR
