Repository dotnet/wpf, pull requests merged in 2022-07, with the labels that each got.

#6706 Fix for Bug 1493635: MenuItems with IsCheckable and StaysOpenOnClick set to true do not announce to Narrator when IsChecked is changed
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/MenuItemAutomationPeer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/MenuItem.cs
Labels: PR

#6750 Fix for Bug 1493635: MenuItems with IsCheckable and StaysOpenOnClick set to true do not announce to Narrator when IsChecked is changed
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/MenuItemAutomationPeer.cs
Labels: PR

#4256 Remove unused local variable `node3Bounds` in MS.Internal.Ink.StrokeNode.GetPointsAtMiddleSegment
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/StrokeNode.cs
Labels: PR, Included in test pass, Queue for test pass

#6209 Remove the unused local variable in PointerTabletDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerTabletDevice.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#6293 Avoid excessive calls to the PropertyValues index getter.
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkElementFactory.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#6547 Ignore NotImplementedException from ITaskbarList
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ShellProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#6614 Translation fix for TextBox_ContextMenu_Cut [cs-CZ]
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.cs.xlf
Labels: PR, Included in test pass, Queue for test pass, localization, Community Contribution

#6619 Replace resource constants with properties in UIAutomationProvider
  eng/WpfArcadeSdk/tools/SystemResources.props
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationProvider/System/Windows/Automation/Provider/AutomationInteropProvider.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationProvider/UIAutomationProvider.csproj
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationProvider/ref/UIAutomationProvider-ref.csproj
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#6622 Fix QueryInsertEmbedded parameter type
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsTextServices.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#6656 Remove sorcery for getting consistent names in the traces
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/MediaTrace.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#6657 Fix ZeroForNow parameter
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsTextServices.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#6756 Update branding to 6.0.8
  eng/Versions.props
Labels: PR

#6755 Update branding to 3.1.28
  eng/Versions.props
Labels: PR

#6773 Fix document format
  Documentation/report-on-adding-new-property.md
Labels: PR, Community Contribution

#6774 Add comment to Wpf.Cpp.props code
  eng/WpfArcadeSdk/tools/Wpf.Cpp.props
Labels: PR, Community Contribution

#6776 update branding to rc1
  eng/Versions.props
Labels: PR, auto_merge

#6781 Fix Zlib and ds lowercase issues
  src/Microsoft.DotNet.Wpf/src/Common/src/Interop/Windows/zlib/zlib.cs
  src/Microsoft.DotNet.Wpf/src/Common/src/System/IO/Compression/DeflateZLib/ZLibNative.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedDSBuilder.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/Compoundfile/CompoundFileDeflateTransform.cs
Labels: PR

#6784 Merging internal commits for release/3.1
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#6783 Merging internal commits for release/6.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#3738 Remove the custom HashSet class
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlObjectReader.cs
Labels: PR, Queue for test pass

#4964 Replacing expensive type checks with "is" checks
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/SynchronizedInputHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/UIElementHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/CommandManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/RoutedCommand.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputElement.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/KeyboardDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerLogic.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispLogic.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispStylusDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Effects/ShaderEffect.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/VisualTreeHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/PresentationSource.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/UIElement.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/UIElement3D.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Annotations/Anchoring/PathNode.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/FrameworkObject.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Helper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Ink/ClipboardProcessor.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PrePostDescendentsWalker.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/BroadcastEventHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/DatePickerTextBox.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/DescendentsWalker.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/DescendentsWalkerBase.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkElement.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Generated/FrameworkContentElement.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Generated/FrameworkElement.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Storyboard.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/StyleHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/TreeWalkHelper.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/ReachDocumentSequenceSerializer.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/ReachDocumentSequenceSerializerAsync.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/ReachFixedDocumentSerializer.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/ReachFixedDocumentSerializerAsync.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/ReachFixedPageSerializer.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/ReachFixedPageSerializerAsync.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/XpsOMFixedPageSerializer.cs
Labels: Performance, PR, Queue for test pass, Community Contribution

#6254 Eliminate memory copy when reading font data
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileStream.cpp
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileStream.h
Labels: PR, Queue for test pass, Community Contribution

#5218 Using the `Clone` method to fast clone the array in StylusPoint
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/StylusPoint.cs
Labels: PR, Queue for test pass

#6691 Fix Invalid_IInputElement resource
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/Strings.resx
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.cs.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.de.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.es.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.fr.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.it.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.ja.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.ko.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.pl.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.pt-BR.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.ru.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.tr.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.zh-Hans.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.zh-Hant.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/RoutedCommand.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/KeyboardDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerStylusDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispStylusDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/TouchDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/PresentationSource.cs
Labels: PR, Queue for test pass, Community Contribution

#4021 Inline VerifyAccess
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/Dispatcher.cs
Labels: Performance, PR, Queue for test pass, Community Contribution

#6793 Fix build when using source generators coming from NuGet packages.
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
Labels: PR, Community Contribution

#6800 Fix build when using source generators coming from NuGet package
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
Labels: PR, Servicing-approved

#1161 Fixing TextBoxView memory leak for 2 seconds after unloading host control
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/TextBoxView.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#4217 CommandParameter invalidates CanExecute
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/MenuItem.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/ButtonBase.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/Hyperlink.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonGallery.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonTextBox.cs
Labels: PR, Investigate, Included in test pass, Queue for test pass, Community Contribution, Under Review

#5296 Merge pattern in DispatcherOperation
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/DispatcherOperation.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#5722 Harden events against race conditions
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaContext.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#6285 Change most non-generic sorts to be generic
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Grid.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/AlphaFlattener/SegmentTree.cs
Labels: PR, Included in test pass, Queue for test pass

#6502 Stop boxing WeakReferenceListEnumerator in PresentationSource use
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/PresentationSource.cs
Labels: PR, Included in test pass, Queue for test pass

#6511 Avoid delegate allocation to call ListCollectionView.PrepareComparer
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/CollectionViewGroupInternal.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/ListCollectionView.cs
Labels: PR, Included in test pass, Queue for test pass

#6848 Workaround missing lib with non-preview images
  azure-pipelines.yml
  azure-pipelines1.yml
  eng/pipeline.yml
Labels: PR

#6770 Update pipeline to run DRTs on PRs
  eng/pipeline.yml
Labels: PR
