Repository dotnet/wpf, pull requests merged in 2022-12, with the labels that each got.

#7336 Update SDK to 8.0.100-alpha.1.22601.6
  global.json
Labels: PR

#7237 Update api-compat.md
  Documentation/api-compat.md
Labels: PR, Community Contribution

#7238 Update ApiCompat.targets
  eng/WpfArcadeSdk/tools/ApiCompat.targets
Labels: PR, Community Contribution

#3008 Use `.Length == 0` instead of `== string.Empty`
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/DataFormat.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/KeyGestureConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/MouseGestureConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/clipboard.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/HyperlinkAutomationPeer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/WindowAutomationPeer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Input/Command/CommandValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XmlnsDictionary.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/PackUriHelper.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/PackageDigitalSignatureManager.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/NameScope.cs
Labels: Performance, PR, Included in test pass, Queue for test pass

#6558 Update XmlnsCache.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XmlnsCache.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#7028 Revert autoConvert for string DataObjects
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextEditorCopyPaste.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#7127 Remove suppression of CA1823
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/ErrorCodes.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#7181 Use ArgumentNullException.ThrowIfNull in System.Xaml
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ArrayExtension.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/StaticExtension.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/TypeExtension.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/NameScope.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/AttachablePropertyServices.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/ServiceProviderContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Events/ObjectCreatedEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriterSettings.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlTextReader.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlXmlReader.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/NameReferenceConverter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/NameScopeDictionary.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Primitives/XamlBackgroundReader.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Primitives/XamlNodeList.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Primitives/XamlNodeQueue.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Replacements/Reference.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlDirective.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlMemberInvoker.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlTypeInvoker.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlDeferLoadAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlException.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlMember.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlObjectReader.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlSchemaContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlServices.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlType.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlTypeName.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlWriter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlXmlWriter.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#7361 Change RestrictiveXamlXmlReader to use an allow list
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/RestrictiveXamlXmlReader.cs
Labels: PR

#7375 Enable Codeql
  eng/pipeline.yml
Labels: PR

#7391 Fix typo in MenuItem comment
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/MenuItem.cs
Labels: PR, Community Contribution

#7164 fix(knowntypes): adding IsReadOnly as known property for TextBox and RichTextBox
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/WpfGeneratedKnownProperties.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/KnownTypes.cs
Labels: PR

#7295 Adding static constructor to StyleHelper class
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/StyleHelper.cs
Labels: PR

#7296 Fixing *-defs width calculation
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Grid.cs
Labels: PR

#7400 Rectify documentation - Use PlatformTarget instead of Platform tag
  Documentation/developer-guide.md
Labels: PR

#7401 Rectifying Commonly Encountered Error section in developers-guide
  Documentation/developer-guide.md
Labels: PR
