Repository dotnet/wpf, pull requests merged in 2022-10, with the labels that each got.

#7135 Run DRTs.
  eng/pipeline.yml
Labels: PR

#7154 Run DRTs only on public pipeline
  eng/pipeline.yml
Labels: PR

#7148 Update .NET8 templates
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/.template.config/template.json
Labels: PR, draft

#7156 Update branding to 3.1.31
  eng/Versions.props
Labels: PR

#7157 Update branding to 6.0.11
  eng/Versions.props
Labels: PR

#7183 Fix pipeline errors
  eng/pipeline.yml
Labels: PR

#7187 Merging internal commits for release/6.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#7184 fix(doc/developer-guide): adding Commonly Encountered Errors section
  Documentation/developer-guide.md
Labels: PR

#7182 Intellisense Update for .NET 7.0 RC2
  eng/Versions.props
Labels: PR

#7219 Update TFM from .net7.0 to .net8.0
  Directory.Build.props
  eng/WpfArcadeSdk/tools/SdkReferences.targets
  global.json
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj
Labels: PR

#5066 Fix GetStreamCore in ContentFilePart
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ContentFilePart.cs
Labels: PR, Included in test pass, Community Contribution

#6714 DataGridColumnBorder caching of Freezable brushes is not actually caching anything at all
  src/Microsoft.DotNet.Wpf/src/Themes/Shared/Microsoft/Windows/Themes/DataGridHeaderBorder.cs
Labels: PR, Included in test pass, Community Contribution

#6785 Fix NullReferenceException in Invariant.get_IsDialogOverrideEnabled
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Invariant.cs
Labels: PR, Included in test pass, Community Contribution

#6857 Check script of combining marks during font fallback
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Classification.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontFace/PhysicalFontFamily.cs
Labels: PR, Included in test pass, Community Contribution

#6889 Replace resource constants with properties in PresentationUI
  eng/WpfArcadeSdk/tools/SystemResources.props
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/DocumentPropertiesDialog.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/DocumentStream.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/FilePresentation.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/PackageController.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/PageTextBox.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/RestrictedTransactionalPackage.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/RightsManagementErrorHandler.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/RightsManagementSuppressedStream.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/StreamProxy.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/TransactionalPackage.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/WriteableOnDemandPackagePart.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/WriteableOnDemandStream.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/XpsViewerException.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/ZoomComboBox.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/CredentialManagerDialog.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/DialogBaseForm.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/DigitalSignatureProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/DocumentApplicationDocumentViewer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/DocumentSignatureManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/PeoplePickerWrapper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RMEnrollmentPage1.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RMEnrollmentPage2.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RMEnrollmentPage3.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RMPermissions.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RMPublishingDialog.RightsTable.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RMPublishingDialog.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RequestedSignatureDialog.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RightsManagementManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RightsManagementProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RightsManagementResourceHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RightsManagementUser.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/SignatureResourceHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/SignatureSummaryDialog.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/SigningDialog.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/PresentationUI.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationUI/SR.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/TenFeetInstallationProgress.xaml.cs
Labels: PR, Included in test pass, Community Contribution

#7091 Fix the stream do not be closed in ImageSourceTypeConverter
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/ImageSourceTypeConverter.cs
Labels: PR, Included in test pass, Community Contribution

#7000 Replace resource constants with properties in PresentationBuildTasks
  eng/WpfArcadeSdk/tools/SystemResources.props
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/ParserExtension.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/CompilerWrapper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/TaskHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/FileClassifier.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass1.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass2.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MergeLocalizationDirectives.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/ResourcesGenerator.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/UidManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/UpdateManifestForBrowserApplication.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/SR.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Media/ParserStreamGeometryContext.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/SR.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/ParsersCommon.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Globalization/LocalizationComments.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/SR.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlRecordWriter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlRecords.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/KnownTypes.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/MarkupExtensionParser.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/StyleXamlParser.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/TemplateXamlParser.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/TreeBuilder.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlParser.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlReaderHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlSerializer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlStyleSerializer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlTemplateSerializer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlTypeMapper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XmlnsCache.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XmlnsDictionary.cs
Labels: PR, Included in test pass, Community Contribution

#7234 [release/6.0] Switch to new images
  azure-pipelines.yml
  eng/pipeline.yml
Labels: PR

#7233 Update branding to 7.0.1
  eng/Versions.props
Labels: PR
