Repository dotnet/wpf, pull requests merged in 2022-06, with the labels that each got.

#6271 Remove substring allocation from Baml2006Reader.Logic_GetFullXmlns
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006Reader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006ReaderInternal.cs
Labels: PR

#6275 Remove some unnecessary StringBuilders
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Color.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ComponentResourceKey.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizationCacheLengthConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/CornerRadiusConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedPage.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/RtfToXamlReader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlMapTable.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlReader.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/Compoundfile/CompoundFileStreamReference.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/Compoundfile/RightsManagementEncryptionTransform.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/Compoundfile/versionPair.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/RightsManagement/User.cs
Labels: PR

#6508 Stop allocating unnecessary StringBuilders in ParsePropertyComments
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Globalization/LocalizationComments.cs
Labels: PR

#6509 Avoid unnecessary StringBuilder reallocation in LookupAndSetLocalizabilityAttribute
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Globalization/LocalizationComments.cs
Labels: PR

#6516 Avoid unnecessary `List<>` wrapper in GetTextRunSpans
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/TextFormatting/FullTextLine.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/TextFormatting/TextRunCacheImp.cs
Labels: PR

#6517 Avoid unnecessary `Collection<T>` wrapper in CombineSources
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/BindingExpressionBase.cs
Labels: PR

#6518 Avoid allocating `Stack<BranchNode>` just to peek at it
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/EventRoute.cs
Labels: PR

#6528 Reuse bool box objects in UncommonField<bool>.SetValue
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/UncommonField.cs
Labels: PR

#6276 Avoid unnecessary byte[] allocation in Baml2006Reader.Process_Header
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006Reader.cs
Labels: PR

#6662 Update branding to 6.0.7
  eng/Versions.props
Labels: PR

#6661 Update branding to 3.1.27
  eng/Versions.props
Labels: PR

#6673 bump up intellisense version
  eng/Versions.props
Labels: PR

#6534 Fix build when using source generators
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs
Labels: PR, Community Contribution

#6681 Merging internal commits for release/6.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#6680 Fix build when using source generators (#6534)
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs
Labels: Servicing-approved

#6698 Fixing the C++/CLI projects failing due to NU1504
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/DirectWriteForwarder.vcxproj
  src/Microsoft.DotNet.Wpf/src/System.Printing/System.Printing.vcxproj
Labels: PR

#6718 Fix build error temporarily to unblock
  src/Microsoft.DotNet.Wpf/src/System.Printing/System.Printing.vcxproj
Labels: PR

#6705 Update Branding to prerelease 7
  eng/Versions.props
Labels: PR

#6709 Fix wpf-debug.targets
  eng/wpf-debug.targets
Labels: PR, Community Contribution

#6720 Fix build error temporarily to unblock (#6718)
  src/Microsoft.DotNet.Wpf/src/System.Printing/System.Printing.vcxproj
Labels: PR
