Repository dotnet/wpf, pull requests merged in 2022-02, with the labels that each got.

#6028 Update versions of .NET and links
  README.md
Labels: PR

#6029 Replace mention of .NET Core 3 to .NET 6
  Documentation/getting-started.md
Labels: PR

#5931 ToolTips in popups (or any context where capture is active)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs
Labels: PR

#6050 Update branding to 6.0.3
  eng/Versions.props
Labels: PR, auto_merge

#6049 Update branding to 5.0.15
  eng/Versions.props
Labels: PR

#5837 Port dirty-rectangle opt-out from 4.8
  src/Microsoft.DotNet.Wpf/src/Common/Graphics/exports.cs
  src/Microsoft.DotNet.Wpf/src/Common/Graphics/wgx_core_types.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/CoreAppContextSwitches.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndTarget.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaContext.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaSystem.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/xml/Resource.xml
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/api/api_utils.cpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/hw/hwdisplayrt.cpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/hw/hwdisplayrt.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/sw/swhwndrt.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/sw/swlib/swhwndrt.cpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/uce/hwndtarget.cpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_misc.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/exports.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/processed/wgx_core_types.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/wgx_core_types_compat.cs
Labels: PR

#6058 show immediately when replacing current tooltip
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs
Labels: PR

#6078 Fix merge errors for #5931 and #5932
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs
Labels: PR

#6017 forward activation message during manipulation (#5836)
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerLogic.cs
Labels: PR, Servicing-approved

#6014 preserve extra info across PeekMessage (#5838)
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsOther.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/Dispatcher.cs
Labels: PR, Servicing-approved

#6019 honor UIA_WindowVisibilityOverridden property (#5839)
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/HwndProxyElementProvider.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Win32/UnsafeNativeMethods.cs
Labels: PR, Servicing-approved

#6018 fix IME vs. property-changed Binding battle (#5840)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/BindingExpressionBase.cs
Labels: PR, Servicing-approved

#6016 fix hang when margin is not a multiple of DPI rounding quantum (#5841)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ItemsControl.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
Labels: PR, Servicing-approved

#6015 rect with negative height is not allowed (#5842)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
Labels: PR, Servicing-approved

#6020 reset ContextMenu whose popup cannot be opened (#5843)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs
Labels: PR, Servicing-approved

#6011 forward activation message during manipulation (#5836)
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerLogic.cs
Labels: PR, Servicing-approved

#6010 preserve extra info across PeekMessage (#5838)
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsOther.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/Dispatcher.cs
Labels: PR, Servicing-approved

#6009 honor UIA_WindowVisibilityOverridden property (#5839)
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/HwndProxyElementProvider.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Win32/UnsafeNativeMethods.cs
Labels: PR, Servicing-approved

#6008 fix IME vs. property-changed Binding battle (#5840)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/BindingExpressionBase.cs
Labels: PR, Servicing-approved

#6012 fix hang when margin is not a multiple of DPI rounding quantum (#5841)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ItemsControl.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
Labels: PR, Servicing-approved

#6013 rect with negative height is not allowed (#5842)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
Labels: PR, Servicing-approved

#6007 reset ContextMenu whose popup cannot be opened (#5843)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs
Labels: PR, Servicing-approved

#6005 forward activation message during manipulation (#5836)
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerLogic.cs
Labels: PR, Servicing-approved

#6062 Port dirty-rectangle opt-out from 4.8 (#5837)
  src/Microsoft.DotNet.Wpf/src/Common/Graphics/exports.cs
  src/Microsoft.DotNet.Wpf/src/Common/Graphics/wgx_core_types.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/CoreAppContextSwitches.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndTarget.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaContext.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaSystem.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/xml/Resource.xml
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/api/api_utils.cpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/hw/hwdisplayrt.cpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/hw/hwdisplayrt.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/sw/swhwndrt.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/sw/swlib/swhwndrt.cpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/uce/hwndtarget.cpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_misc.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/exports.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/processed/wgx_core_types.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/wgx_core_types_compat.cs
Labels: PR, Servicing-approved

#6001 preserve extra info across PeekMessage (#5838)
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsOther.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/Dispatcher.cs
Labels: PR, Servicing-approved

#6000 honor UIA_WindowVisibilityOverridden property (#5839)
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/HwndProxyElementProvider.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Win32/UnsafeNativeMethods.cs
Labels: PR, Servicing-approved

#6006 fix IME vs. property-changed Binding battle (#5840)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/BindingExpressionBase.cs
Labels: PR, Servicing-approved

#6004 fix hang when margin is not a multiple of DPI rounding quantum (#5841)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ItemsControl.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
Labels: PR, Servicing-approved

#6003 rect with negative height is not allowed (#5842)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
Labels: PR, Servicing-approved

#5999 reset ContextMenu whose popup cannot be opened (#5843)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs
Labels: PR, Servicing-approved

#6063 ToolTips in popups (or any context where capture is active) (#5931)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs
Labels: PR, Servicing-approved

#6064 show immediately when replacing current tooltip (#6058)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs
Labels: PR, Servicing-approved

#6071 Pull release/6.0 into main
  eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
  global.json
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs
Labels: PR

#6088 Merging internal commits for release/6.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/pipeline.yml
Labels: PR

#6089 Merging internal commits for release/5.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#6100 Revert "[release/6.0] Update dependencies from dnceng/internal/dotnet-wpf-int"
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#6098 Remove and update outdated dependencies
  eng/Versions.props
  global.json
Labels: area-infrastructure, PR, auto_merge

#6099 Pin assembly versions to prevent revving those in servicing releases
  eng/Versions.props
  packaging/Microsoft.DotNet.Wpf.GitHub/Check-AssemblyVersions.ps1
  packaging/Microsoft.DotNet.Wpf.GitHub/Directory.Build.targets
Labels: PR

#5964 Improve Linux build
  build.sh
  eng/WpfArcadeSdk/Sdk/Sdk.props
  eng/WpfArcadeSdk/Sdk/Sdk.targets
  eng/common/native/install-dotnet-api-docs_net5.0.sh
  eng/common/native/install-net-framework-48-ref-assemblies.sh
  eng/common/native/install-strawberry-perl.sh
  src/Microsoft.DotNet.Wpf/src/PresentationCore/ref/PresentationCore-ref.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework-ref.csproj
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj
  src/Microsoft.DotNet.Wpf/src/System.Xaml/ref/System.Xaml-ref.csproj
Labels: area-infrastructure, PR

#6034 Update MSBuild tasks
  eng/WpfArcadeSdk/tools/ExtendedAssemblyInfo.targets
Labels: PR, Queue for test pass

#6101 Pin assembly versions to prevent revving those in servicing releases
  eng/Versions.props
  packaging/Microsoft.DotNet.Wpf.GitHub/Check-AssemblyVersions.ps1
  packaging/Microsoft.DotNet.Wpf.GitHub/Directory.Build.targets
Labels: PR, Servicing-approved

#6125 Adding msbot configuration file, as per recommendation by fabricbot team
  .github/fabricbot.json
Labels: PR

#6122 Remove or replace policheck violations from the code
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/Win32/UnsafeNativeMethodsPenimc.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/webbrowsersite.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/AccessorTable.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/PropertyPathWorker.cs
Labels: PR

#6134 Update branding to Preview 3
  eng/Versions.props
Labels: PR, auto_merge

#6170 Fix the comment in DefaultRestoreFocusMode property
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/KeyboardDevice.cs
Labels: PR, auto_merge

#6182 Update GenAPI additional parameter usage
  eng/Versions.props
  eng/WpfArcadeSdk/tools/GenApi.props
Labels: PR

#6148 Add rules to fabricbot
  .github/fabricbot.json
Labels: PR
