Repository dotnet/wpf, pull requests merged in 2023-02, with the labels that each got.

#4317 Remove expressions that have always been known in PropertyChangedEventManager
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/ComponentModel/PropertyChangedEventManager.cs
Labels: PR, Included in test pass, Community Contribution

#5393 Improve LookupContentTypeForImageUri performance in XpsFixedPageReaderWriter.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsFixedPageReaderWriter.cs
Labels: PR, Included in test pass, Community Contribution

#7396 Remove Source Generator workaround
  Directory.Build.targets
Labels: PR, Included in test pass, Community Contribution

#7408 Update DatePicker.FirstDayOfWeek on Language change
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DatePicker.cs
Labels: PR, Included in test pass, Community Contribution

#7488 Adding release/8.0 to azure-pipeline.yml
  azure-pipelines.yml
Labels: PR

#7490 Enable in-build signing based on branch
  azure-pipelines.yml
Labels: PR

#7491 [release/8.0-preview1] Enable in-build signing based on branch
  azure-pipelines.yml
Labels: PR

#1963 avoid boxing for xxxAnimationUsingKeyFrames
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/BooleanAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/ByteAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/CharAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/ColorAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/DecimalAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/DoubleAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/Int16AnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/Int32AnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/Int64AnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/MatrixAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/ObjectAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/Point3DAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/PointAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/QuaternionAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/RectAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/Rotation3DAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/SingleAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/SizeAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/StringAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/Vector3DAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Generated/VectorAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/ThicknessAnimationUsingKeyFrames.cs
Labels: Performance, PR, Included in test pass, Community Contribution

#7495 API Review Process for WPF
  .github/ISSUE_TEMPLATE/02_api_proposal.yml
  Documentation/project/api-review-process.md
Labels: PR

#7496 New bug report template
  .github/ISSUE_TEMPLATE/01_bug_report.yml
Labels: PR

#7497 Remove old bug template and fixed links
  .github/ISSUE_TEMPLATE/bug_report.md
  Documentation/project/api-review-process.md
Labels: PR

#7512 Update branding to 7.0.4
  eng/Versions.props
Labels: PR

#7511 Update branding to 6.0.15
  eng/Versions.props
Labels: PR

#7504 CTP automation, dotnet test install and bin replacement
  eng/common/dotnet-test-install.ps1
  eng/wpfautomatedtests.yml
Labels: PR

#5216 Add the SelectableProperty in Selector.
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Selector.cs
Labels: PR, Community Contribution

#7534 Merging internal commits for release/7.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#7533 Merging internal commits for release/6.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#7541 WPF Test Automation
  azure-pipelines1.yml
  eng/wpfautomatedtests.yml
Labels: PR

#7553 Fix build errors due to specific build
  eng/pipeline.yml
Labels: PR

#7554 WPF roadmap 2023
  roadmap.md
Labels: PR

#7578 Update branding to 8.0-preview3
  eng/Versions.props
Labels: PR
