Repository dotnet/wpf, pull requests merged in 2023-04, with the labels that each got.

#6510 Avoid boxing in UniqueEventHelper
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/UniqueEventHelper.cs
Labels: PR, Included in test pass, Queue for test pass

#7168 Include missing APIs in reference assembly
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/System.Windows.Controls.Ribbon-ref-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/System.Windows.Controls.Ribbon-ref.baseline.txt
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/ref/System.Windows.Controls.Ribbon.cs
Labels: PR, Included in test pass, Queue for test pass

#7545 GlyphSerializer rounding fix
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/GlyphsSerializer.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#7568 Disposing page stream eagerly
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedFindEngine.cs
Labels: PR, Included in test pass, Queue for test pass

#7693 Adding documentation for debugging PBT
  Documentation/developer-guide.md
Labels: PR

#7695 Update branding to 6.0.17
  eng/Versions.props
Labels: PR

#7696 Update branding to 7.0.6
  eng/Versions.props
Labels: PR

#7707 Merging internal commits for release/7.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#7706 Merging internal commits for release/6.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#7713 Update branding to 8-preview5
  eng/Versions.props
Labels: PR

#7720 Github action to backport PRs to branch
  .github/workflows/backportPRs.yml
Labels: PR

#1167 Fixing validation adorner for not yet visible controls
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Validation.cs
Labels: PR, Included in test pass, Community Contribution

#6538 Simplify dwrite.dll loading process
  src/Microsoft.DotNet.Wpf/src/Shared/cpp/dwriteloader.cpp
Labels: PR, Included in test pass, Community Contribution

#6553 optimistic TrackValue check, supporting not anymore connected columns
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGrid.cs
Labels: PR, Included in test pass, Community Contribution

#7680 Replace String.CompareOrdinal to string.Equals in KnownTypes Part 2
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/KnownTypes.cs
Labels: PR, Included in test pass, Community Contribution

#7691 Cleanup following replacing resource constants with properties.
  eng/WpfArcadeSdk/tools/SystemResources.props
  src/Microsoft.DotNet.Wpf/src/Common/src/System/SR.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Input.Manipulations/System.Windows.Input.Manipulations.csproj
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/UIAutomationTypes.csproj
Labels: PR, Included in test pass, Community Contribution

#7775 Disabled tasks after RunTests
  eng/pipeline.yml
Labels: PR

#7778 Disabled tasks after RunTests (#7775)
  eng/pipeline.yml
Labels: PR, auto_merge

#7780 [8.0-preview4] Disable warnings CS0672, SYSLIB00(11,50,51)
  src/Microsoft.DotNet.Wpf/cycle-breakers/PresentationFramework/PresentationFramework.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/AnimationException.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/InvalidWMPVersionException.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/DataStreams.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/Pts.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Frame.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PrintDialogException.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/ValueUnavailableException.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlParseException.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Navigation/Journal.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Navigation/NavigationService.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceReferenceKeyNotFoundException.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/XpsViewerException.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Exceptions/XpsException.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintSystemExceptions/PrintSystemException.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/ref/ReachFramework.cs
  src/Microsoft.DotNet.Wpf/src/System.Printing/ref/System.Printing.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/GenericTypeNameParser.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlTypeInvoker.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlException.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/ref/System.Xaml.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/ElementNotAvailableException.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/ElementNotEnabledException.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/NoClickablePointException.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/ProxyAssemblyNotLoadedException.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/ref/UIAutomationTypes.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/RightsManagement/Exceptions.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/ref/WindowsBase.cs
Labels: PR

#211 Fix bug in `XamlTypeInvoker.GetAddMethod` if there is no such match
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlTypeInvoker.cs
Labels: PR, Included in test pass, Community Contribution

#215 Fix NullReferenceException in `new ContentWrapperAttribute(null).GetHashCode`
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ContentWrapperAttribute.cs
Labels: PR, Included in test pass, Community Contribution

#220 Fix NullReferenceException in XamlType.Equals/XamlType.GetHashCode
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlType.cs
Labels: PR, Included in test pass, Community Contribution
