Repository dotnet/wpf, pull requests merged in 2023-06, with the labels that each got.

#7901 Update branding to 7.0.8
  eng/Versions.props
Labels: PR

#7900 Update branding to 6.0.19
  eng/Versions.props
Labels: PR

#7903 Fixing errors due to dotnet versions during test.
  eng/pipeline.yml
Labels: PR

#206 Remove dead code from XamlNamespace generic parsing
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/Reflector.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlNamespace.cs
Labels: PR, Included in test pass, Community Contribution

#7730 Use TextAlignment for TextBox.GetCharacterIndexFromPoint
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/TextBoxView.cs
Labels: Included in test pass

#139 Remove dead code from ReflectionHelper
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/Strings.resx
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.cs.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.de.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.es.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.fr.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.it.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.ja.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.ko.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.pl.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.pt-BR.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.ru.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.tr.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.zh-Hans.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.zh-Hant.xlf
  src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/ReflectionHelper.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/ExceptionStringTable.txt
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/Strings.resx
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.cs.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.de.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.es.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.fr.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.it.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.ja.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.ko.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.pl.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.pt-BR.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.ru.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.tr.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.zh-Hans.xlf
  src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.zh-Hant.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/Strings.resx
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.cs.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.de.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.es.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.fr.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.it.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.ja.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.ko.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.pl.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.pt-BR.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.ru.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.tr.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.zh-Hans.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.zh-Hant.xlf
Labels: PR, Included in test pass, Community Contribution

#7743 Allow right click in system menu
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemCommands.cs
Labels: PR, Included in test pass, Community Contribution

#7794 Improve font performance in FamilyCollection.LookupFamily
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FamilyCollection.cs
Labels: Performance, PR, Included in test pass, Community Contribution

#7833 Replace String.CompareOrdinal to string.Equals Part 3
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/IO/Packaging/PseudoWebRequest.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/clipboard.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/IO/Packaging/ContentDescriptor.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlTypeMapper.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/IO/Packaging/PackagingUtilities.cs
Labels: PR, Included in test pass, Community Contribution

#7836 Modernize the empty string checking in ContentType
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/ContentType.cs
Labels: PR, Included in test pass, Community Contribution

#7920 Merging internal commits for release/6.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/AppModelKnownContentFactory.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/MimeObjectFactory.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/ParserContext.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/RestrictiveXamlXmlReader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/WpfXamlLoader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlReader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Navigation/NavigationService.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceDictionary.cs
Labels: PR

#7921 Merging internal commits for release/7.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/AppModelKnownContentFactory.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/MimeObjectFactory.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/ParserContext.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/RestrictiveXamlXmlReader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/WpfXamlLoader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlReader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Navigation/NavigationService.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceDictionary.cs
Labels: PR

#7905 Fix intellisense not working in .NET7
  eng/Versions.props
  eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
Labels: PR, Servicing-approved

#7906 Fix Intellisense in Visual Studio for wpf
  eng/Versions.props
  eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
Labels: PR

#7926 WPF MSRC Fix port for CVE-2023-24895
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/AppModelKnownContentFactory.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/MimeObjectFactory.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/ParserContext.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/RestrictiveXamlXmlReader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/WpfXamlLoader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlReader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Navigation/NavigationService.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceDictionary.cs
Labels: PR

#7948 Update branding to 6.0.20
  eng/Versions.props
Labels: PR

#7949 Update branding to 7.0.9
  eng/Versions.props
Labels: PR

#7956 Update branding from preview6 to 7
  eng/Versions.props
Labels: PR

#7923 Fix sc Color.ToString()
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Color.cs
Labels: PR, Queue for test pass, Community Contribution

#5571 Adding GreaterThanZero to DoubleUtil.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Helper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/ParagraphVisual.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Border.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridColumnCollection.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/FlowDocumentReader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/FlowDocumentScrollViewer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/GroupItem.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ListBox.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ScrollViewer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/SinglePageViewer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Slider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TreeViewItem.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/DoubleUtil.cs
Labels: Performance, PR, Included in test pass, Community Contribution

#7345 Fall back to `Window.Title` if `GetWindowText` fails
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/WindowAutomationPeer.cs
Labels: PR, Included in test pass, Community Contribution

#7395 Use Microsoft.CodeAnalysis.NetAnalyzers
  eng/Versions.props
  eng/WpfArcadeSdk/Sdk/Sdk.props
  eng/WpfArcadeSdk/tools/CodeAnalysis.props
  eng/WpfArcadeSdk/tools/CodeAnalysis.targets
  eng/WpfArcadeSdk/tools/CodeAnalysis/CodeAnalysis.src.globalconfig
  eng/WpfArcadeSdk/tools/CodeAnalysis/WpfCodeAnalysis.ruleset
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/StaticExtensionConverter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/TypeExtensionConverter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlTypeInvoker.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlType.cs
Labels: PR, Included in test pass, Community Contribution

#7729 Unblock AltGr+Oem2/5 typing inside ListBox
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ListBox.cs
Labels: Included in test pass

#7846 Removing xamltypemapper clearance from finally in compile function
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs
Labels: PR, Included in test pass

#7910 Fix InputEventArgs.Timestamp field
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputEventArgs.cs
Labels: PR, Included in test pass, Community Contribution
