Repository dotnet/wpf, pull requests merged in 2023-01, with the labels that each got.

#7412 Update branding to 7.0.3
  eng/Versions.props
Labels: PR

#7411 Update branding to 6.0.14
  eng/Versions.props
Labels: PR

#7371 Adding static constructor to StyleHelper class
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/StyleHelper.cs
Labels: PR, Servicing-approved, .NET 7 Servicing PR

#7213 Updated precedence for project templates
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/.template.config/template.json
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/.template.config/template.json
Labels: PR, Servicing-approved, .NET 7 Servicing PR

#7349 fix(column-resize): adding opt-out switch for column resize and column sorting features by keyboard inputs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridCell.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ListBox.cs
Labels: PR

#7425 Fixing CA2200: Rethrow to preserve stack details
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlReaderHelper.cs
Labels: PR

#7350 fix(column-resize): adding opt-out switch for column resize and column sorting features by keyboard inputs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridCell.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ListBox.cs
Labels: PR, .NET 7 Servicing PR

#7429 Separate official and test pipelines
  azure-pipelines1.yml
  eng/wpfautomatedtests.yml
Labels: PR

#7426 Revert "avoid boxing (#4220)"
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/UncommonField.cs
Labels: PR

#7443 Remove unwanted steps in wpf automated tests pipeline.
  azure-pipelines1.yml
  eng/wpfautomatedtests.yml
Labels: PR

#7435 Merging internal commits for release/7.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/RestrictiveXamlXmlReader.cs
Labels: PR

#7434 Merging internal commits for release/6.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/RestrictiveXamlXmlReader.cs
Labels: PR

#7437 Merging internal commits for release/3.1
  azure-pipelines.yml
  eng/pipeline.yml
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/RestrictiveXamlXmlReader.cs
Labels: PR

#6693 Remove SafeReflectionInvoker
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/EventConverter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Runtime/ClrObjectRuntime.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/SafeReflectionInvoker.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlMemberInvoker.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlTypeInvoker.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlValueConverter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlType.cs
Labels: PR, Queue for test pass, Community Contribution

#6862 Fix ItemsControl Automation
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ItemsControl.cs
Labels: PR, Queue for test pass, Community Contribution

#4635 Adding the popup to empty List directly in Popup.RegisterPopupWithPlacementTarget
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs
Labels: PR, Queue for test pass, Community Contribution

#7475 download latest artifacts rather than specific
  eng/wpfautomatedtests.yml
Labels: PR

#7476 update .NET version for replacing assemblies.
  eng/copy-wpf.ps1
Labels: PR

#7480 set path vars for testhost install
  eng/wpfautomatedtests.yml
Labels: PR, auto_merge
