Repository dotnet/wpf, pull requests merged in 2023-08, with the labels that each got.

#8064 Update branding to 7.0.11
  eng/Versions.props
Labels: PR

#8063 Update branding to 6.0.22
  eng/Versions.props
Labels: PR

#8061 Fix for WPF build error post VS 17.7.0 preview 5.0 update
  eng/WpfArcadeSdk/tools/Wpf.Cpp.props
Labels: PR

#8074 Merging internal commits for release/7.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#8073 Merging internal commits for release/6.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#7684 Enabling Hardware Acceleration on RDP
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/CoreAppContextSwitches.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/AppContextDefaultValues.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaSystem.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/UnsafeNativeMethodsMilCoreApi.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/common/d3dutils.cpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/common/display.cpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/common/renderoptions.cpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/common/renderoptions.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/dll/wpfgfx.def
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/hw/hwbitmapcolorsource.cpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/meta/desktoprt.cpp
Labels: PR

#8086 Guard with null checks in adorners
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/RawStylusInput.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/StickyNote/StickyNoteAnnotations.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/TemplatedAdorner.cs
Labels: PR

#8099 Updated main to 9.0-alpha1
  eng/Versions.props
Labels: PR

#8042 Replace String.CompareOrdinal to string.Equals Final Part
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Markup/XmlLanguage.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/IO/Packaging/XamlFilter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/IO/Packaging/XmlGlyphRunInfo.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Image.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlMapTable.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlReaderHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XmlnsCache.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsFixedPageReaderWriter.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsManager.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CaseInsensitiveOrdinalStringComparer.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CompoundFile/CompoundFileStorageReference.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CompoundFile/CompoundFileStreamReference.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CompoundFile/VersionedStreamOwner.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CustomSignedXml.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/PackUriHelper.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/StorageBasedPackageProperties.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/XmlDigitalSignatureProcessor.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/XmlSignatureManifest.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/XmlSignatureProperties.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/Security/RightsManagement/ClientSession.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/Security/RightsManagement/IssuanceLicense.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/CompoundFile/FormatVersion.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/CompoundFile/StreamInfo.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/EncryptedPackage.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/PackageDigitalSignatureManager.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/RightsManagement/LocalizedNameDescriptionPair.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/RightsManagement/UseLicense.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/RightsManagement/User.cs
Labels: PR, Queue for test pass, Community Contribution

#7734 Avoid crashing if temporary file cannot be deleted
  src/Microsoft.DotNet.Wpf/src/Shared/System/IO/FileHelper.cs
Labels: Queue for test pass

#7557 Fixing the AssemblyName in temporary project file for GenerateTemporaryTargetAssembly task
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs
Labels: PR, Queue for test pass

#6535 Fix build when using Razor source generator
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs
Labels: PR, Queue for test pass, Community Contribution

#207 Cleanup System.Windows.Markup code
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/AcceptedMarkupExtensionExpressionTypeAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ArrayExtension.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ConstructorArgumentAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ContentPropertyAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/DateTimeValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/DependsOnAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/IComponentConnector.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/INameScope.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/IProvideValueTarget.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/IUriContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/IValueSerializerContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/IXamlTypeResolver.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/MarkupExtension.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/MarkupExtensionReturnTypeAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/NameScopePropertyAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/NullExtension.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/PropertyDefinition.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/RootNamespaceAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/StaticExtension.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/StaticExtensionsToInstanceDescriptorsConverter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/TrimSurroundingWhitespaceAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/TypeExtension.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/TypeExtensionConverter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/UidPropertyAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/UsableDuringInitializationAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/WhitespaceSignificantCollectionAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XData.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XamlSetMarkupExtensionAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XamlSetMarkupExtensionEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XamlSetTypeConverterAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XamlSetTypeConverterEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XmlLangPropertyAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XmlnsCompatibleWithAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XmlnsDefinitionAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XmlnsPrefixAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/NameScope.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/NameValidationHelper.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/ms/Internal/Markup/StringValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/ms/Internal/Markup/TypeConverterValueSerializer.cs
Labels: PR, Queue for test pass, Community Contribution

#8133 Fixed PublishTestResult task and renamed Run xUnit Test task
  eng/pipeline.yml
Labels: PR

#8059 Perl version upgrade
  eng/Versions.props
  global.json
Labels: PR
