Repository dotnet/wpf, pull requests merged in 2023-05, with the labels that each got.

#196 Move files to the right directory
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/NameReferenceConverter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/Reference.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/UsableDuringInitializationAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XData.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XamlDeferLoadAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/LineInfo.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/NameScope.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/NameValidationHelper.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/ReaderBaseDelegate.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/ReaderDelegate.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/ReaderMultiIndexDelegate.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/AllowedMemberLocations.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlTypeTypeConverter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/WriterDelegate.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlBackgroundReader.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlNodeList.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlNodeQueue.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlSubreader.cs
Labels: PR, Included in test pass, Community Contribution

#7790 Update branding to 7.0.7
  eng/Versions.props
Labels: PR

#7789 Update branding to 6.0.18
  eng/Versions.props
Labels: PR

#7741 Updating README.md and docs
  Documentation/developer-guide.md
  README.md
Labels: PR

#7773 Updated pipeline to install .NET 8 Preview 3 after build
  eng/pipeline.yml
Labels: PR, auto_merge

#7809 Re-enabling test on CI
  eng/pipeline.yml
Labels: PR

#7853 Update branding of 8.0 from preview5 to preview6
  eng/Versions.props
Labels: PR

#7876 Removing Policheck violation from roadmap.md
  roadmap.md
Labels: PR
