Repository dotnet/wpf, pull requests merged in 2023-03, with the labels that each got.

#7333 Tooltip Direct Manipulation Fix
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs
Labels: PR

#7599 Update branding to 6.0.16
  eng/Versions.props
Labels: PR

#7600 Update branding to 7.0.5
  eng/Versions.props
Labels: PR

#7417 Tooltip Direct Manipulation Fix
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs
Labels: PR, Servicing-approved

#7418 Tooltip Direct Manipulation Fix
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs
Labels: PR, Servicing-approved

#7611 Remove policheck violations from the code
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/WebBrowserSite.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/hw/waffling-and-packing.txt
Labels: PR

#7616 Merging internal commits for release/7.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#7615 Merging internal commits for release/6.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#7626 Update build image in the release branch 7.0
  azure-pipelines1.yml
Labels: PR

#7610 Publish test artifacts and show test results
  eng/pipeline.yml
Labels: PR

#7638 Remove System.Drawing.Common coherent package dependency
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#7639 Fix official build break
  eng/pipeline.yml
Labels: PR

#7486 Replace Dictionary with HashSet
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FontSourceCollection.cs
  src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/XmlCompatibilityReader.cs
Labels: Performance, PR, Included in test pass, Queue for test pass, Community Contribution

#7500 Replace String.CompareOrdinal to string.Equals in KnownTypes
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/KnownTypes.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#7556 Use project ChecksumAlgorithm in code-behind.
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/CompilerWrapper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass1.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#7644 Update dotnet install script location for tests
  azure-pipelines1.yml
  dotnet-test-install.ps1
  eng/wpfautomatedtests.yml
Labels: PR

#7646 Branding to preview 4
  eng/Versions.props
Labels: PR, auto_merge

#4044 In ClrObjectRuntime, move the object definition next to the code used
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Runtime/ClrObjectRuntime.cs
Labels: PR, Included in test pass, Queue for test pass, Community Contribution

#7666 Adding null check for checksumalgorithm
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs
Labels: PR

#7668 Adding null check for ChecksumAlgorithm (#7666)
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs
Labels: PR, Servicing-approved

#7669 Fix typo
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/MediaElement.cs
Labels: PR, Community Contribution

#7675 Fixing switch for data grid sort using keyboard shortcut
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridCell.cs
Labels: PR

#7678 Disable WriteOnlyWhenDifferent if Overwrite=false
  eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
Labels: PR
