Repository dotnet/wpf, pull requests merged in 2023-12, with the labels that each got.

#8501 Add PR trigger for win11 theming branch
  azure-pipelines.yml
Labels: PR

#8478 Adding a Null check for data in SetData function
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs
Labels: PR

#6428 Try fix the first point in StylusPlugin in high DPI
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/PenContexts.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispLogic.cs
Labels: PR, Included in test pass, Community Contribution

#745 Define Value property of Setter as XAML content property
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/System.Windows.Controls.Ribbon-ref-Net48.baseline.txt
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/UIAutomationProvider-ref.baseline.txt
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Setter.cs
Labels: Enhancement Requested, * NO MERGE *, not-right-now, PR, API Review Requested

#8570 Setup a new branch for Win11 Theming
  Documentation/projects-and-assemblies.md
  Microsoft.Dotnet.Wpf.sln
  eng/WpfArcadeSdk/tools/GenApi.props
  eng/WpfArcadeSdk/tools/ShippingProjects.props
  eng/WpfArcadeSdk/tools/WpfProjectReference.targets
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref.baseline.txt
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/OtherAssemblyAttrs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Button.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ControlAppearance.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/IIconControl.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/IconElement/FontIcon.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/IconElement/IconElement.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/IconElement/IconElementConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/IconElement/IconSourceElement.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/IconElement/IconSourceElementConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/IconElement/ImageIcon.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/IconElement/SymbolIcon.bmp
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/IconElement/SymbolIcon.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/IconSource/FontIconSource.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/IconSource/IconSource.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/IconSource/SymbolIconSource.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/SymbolExtensions.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/SymbolFilled.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/SymbolGlyph.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/SymbolRegular.cs
  src/Microsoft.DotNet.Wpf/src/Shared/RefAssemblyAttrs.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonButton.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/ref/System.Windows.Controls.Ribbon.cs
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/PresentationFramework.Win11.csproj
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/Accent.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/DefaultContextMenu.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/DefaultFocusVisualStyle.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/Fonts.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/Fonts/FluentSystemIcons-Filled.ttf
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/Fonts/FluentSystemIcons-Regular.ttf
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/Palette.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/PresentationFramework.Win11.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/StaticColors.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/Theme/HC1.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/Theme/HC2.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/Theme/HCBlack.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/Theme/HCWhite.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/Theme/Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/Typography.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/Variables.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Button.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/CheckBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/RadioButton.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ToolTip.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/ref/PresentationFramework.Win11-ref.csproj
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/ref/PresentationFramework.Win11.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/OtherAssemblyAttrs.cs
Labels: PR

#8566 Fix comment typo in Stroke2.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Ink/Stroke2.cs
Labels: PR, Community Contribution

#8577 Fix CI - * not working for feature branch
  azure-pipelines.yml
Labels: PR

#8575 Window styling and Theming API
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref.baseline.txt
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Appearance/ApplicationAccentColorManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Appearance/ApplicationTheme.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Appearance/ApplicationThemeManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Appearance/ObservedWindow.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Appearance/ResourceDictionaryManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Appearance/SystemTheme.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Appearance/SystemThemeManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Appearance/SystemThemeWatcher.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Appearance/ThemeChangedEvent.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Appearance/WindowBackdrop.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Appearance/WindowBackgroundManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Extensions/ColorExtensions.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Hardware/DisplayDpi.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/Dwapi.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/Libraries.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/UnsafeNativeMethodsWindow.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/UnsafeReflection.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/DpiHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/Utilities.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/WindowBackdropType.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/SafeNativeMethodsCLR.cs
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Controls/ClientAreaBorder.cs
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Window.xaml
Labels: PR

#8589 Fix Button Appearance and Calendar Button not showing
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/SymbolIconExtension.cs
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Button.xaml
Labels: PR

#8587 Adding win11 styles to Calendar
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Calendar.xaml
Labels: PR

#8578 Adding win11 styles to progressbar, label and statusbar
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Label.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ProgressBar.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/StatusBar.xaml
Labels: PR

#8590 Adding Win11 Styles to Context menu
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ContextMenu.xaml
Labels: PR

#8586 Applying win11 theme to textblock
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/TextBlock.xaml
Labels: PR

#8584 Adding win11 styles to ScrollBar and ScrollViewer
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ScrollBar.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ScrollViewer.xaml
Labels: PR

#8592 Adding Win11 Styles to ListView and ListViewItem
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ListView.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ListViewItem.xaml
Labels: PR

#8594 Adding win11 styles to DataGrid
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref.baseline.txt
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGrid.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/FallbackBrushConverter.cs
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/DataGrid.xaml
Labels: PR

#8583 Adding win11 styles to Expander and DatePicker
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref.baseline.txt
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/AnimationFactorToValueConverter.cs
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/DatePicker.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Expander.xaml
Labels: PR

#8595 Adding win11 styles to Menu and MenuItem
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/PresentationFramework.Win11.csproj
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Menu.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Menu.xaml.cs
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/MenuItem.xaml
Labels: PR

#8610 Fix spelling error in `ISpellerSegment`
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/SpellerInteropBase.cs
Labels: PR, Community Contribution
