Repository dotnet/wpf, pull requests merged in 2024-01, with the labels that each got.

#8604 Add Control and theme dict structures
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref.baseline.txt
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Appearance/ApplicationThemeManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ElementPlacement.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PassiveScrollViewer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TextBox.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Input/IRelayCommand.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Input/IRelayCommand{T}.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Input/RelayCommand{T}.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/ControlsDictionary.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/ThemeResource.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/ThemeResourceExtension.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/ThemesDictionary.cs
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/PresentationFramework.Win11.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Button.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/TextBox.xaml
Labels: PR

#8607 Changed x:Class attribute value for win11 ContextMenu control styles
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ContextMenu.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ContextMenu.xaml.cs
Labels: PR

#8581 Adding win11 styles to RichTextBox and Separator
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref.baseline.txt
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/RichTextBox.cs
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/RichTextBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Separator.xaml
Labels: PR

#8625 Update branding to 8.0.2
  eng/Versions.props
Labels: PR

#8624 Update branding to 7.0.16
  eng/Versions.props
Labels: PR

#8623 Update branding to 6.0.27
  eng/Versions.props
Labels: PR

#8619 Added null check in Textbox control on CanExecuteChanged to avoid exception
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Input/RelayCommand{T}.cs
Labels: PR, Win 11 Theming

#8593 Adding Win11 Styles to Combo box
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ComboBox.xaml
Labels: PR, Win 11 Theming

#8588 Adding Win11 Styles to ToggleButton, ListBox, ListBoxItem, Slider, ToolBar
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ListBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ListBoxItem.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Slider.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ToggleButton.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ToolBar.xaml
Labels: PR, Win 11 Theming

#8579 Applying Win11 Styles to TabControl, Frame, Page
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Frame.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Page.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/TabControl.xaml
Labels: PR, Win 11 Theming

#8603 Adding Win11 Styles to TreeView and TreeViewItem
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/TreeView.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/TreeViewItem.xaml
Labels: PR, Win 11 Theming

#8636 Import xaml styles in the integrated styles page
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/PresentationFramework.Win11.xaml
Labels: PR

#8637 Moving ThemesDictionary and ControlsDictionary to parent namespace
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref.baseline.txt
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ControlsDictionary.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemesDictionary.cs
Labels: PR

#8638 Update ApplicationThemeManager.cs to use correct namespace
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Appearance/ApplicationThemeManager.cs
Labels: PR

#8648 Add missing FontIcon and ImageIcon classes
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref.baseline.txt
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/FontIconExtension.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/IconElement/ImageIcon.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ImageIconExtension.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/SymbolExtensions.cs
Labels: PR

#8656 Merging internal commits for release/6.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/PackageDigitalSignatureManager.cs
Labels: PR

#8658 Merging internal commits for release/8.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/PackageDigitalSignatureManager.cs
Labels: PR

#8657 Merging internal commits for release/7.0
  NuGet.config
  azure-pipelines.yml
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/PackageDigitalSignatureManager.cs
Labels: PR

#8500 Use ObjectDisposedException throw helper across codebase
  src/Microsoft.DotNet.Wpf/src/Common/src/System/IO/Compression/DeflateZLib/ZLibNative.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/IO/Packaging/NetStream.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/IO/Packaging/ResponseStream.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/GestureRecognizer/NativeRecognizer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/IO/Packaging/PackWebResponse.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Ink/GestureRecognizer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/TabletDeviceCollection.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispTabletDeviceCollection.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/ByteStreamGeometryContext.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/CompositionTarget.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/DrawingDrawingContext.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/EventProxy.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaContextNotificationWindow.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/RenderDataDrawingContext.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/WindowsRuntime/Generated/WinRT/ObjectReference.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/DocumentGridPage.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/HostedElements.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/DocumentPageView.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/WebBrowser.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006Reader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/Document.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/PeoplePickerWrapper.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsDocument.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsFixedDocumentReaderWriter.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsManager.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintConfig/FallbackPTProvider.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintConfig/PTConverter.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintConfig/PTManager.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintConfig/PTProvider.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/IO/Packaging/PackagingUtilities.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/IO/SynchronizingStream.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/ReaderWriterLockSlimWrapper.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlXmlReader.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/ReaderDelegate.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/ReaderMultiIndexDelegate.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/WriterDelegate.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlBackgroundReader.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlSubreader.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlXmlWriter.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CompoundFile/StreamWithDictionary.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/Security/RightsManagement/ClientSession.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/RightsManagement/SecureEnvironment.cs
Labels: PR, Included in test pass, Community Contribution

#8489 More uses of ArgumentOutOfRangeException.ThrowIf* to replace custom error messages
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/TextFormatting/TextFormatterImp.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/ExceptionStringTable.txt
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/Strings.resx
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.cs.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.de.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.es.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.fr.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.it.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.ja.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.ko.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.pl.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.pt-BR.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.ru.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.tr.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.zh-Hans.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Resources/xlf/Strings.zh-Hant.xlf
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/FontStretch.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/FontWeight.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/FormattedText.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/GlyphRun.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/JpegBitmapEncoder.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/WmpBitmapEncoder.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/WriteableBitmap.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaPlayerState.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/textformatting/TextParagraphCache.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/CharacterBuffer.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/Strings.resx
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.cs.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.de.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.es.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.fr.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.it.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.ja.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.ko.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.pl.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.pt-BR.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.ru.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.tr.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.zh-Hans.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/Resources/xlf/Strings.zh-Hant.xlf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Int32Rect.cs
Labels: PR, Included in test pass, Community Contribution

#8612 Adding win11 styles to PasswordBox
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref.baseline.txt
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PasswordBox.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ElementPlacement.cs
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/PasswordBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/TextBox.xaml
Labels: PR, Win 11 Theming

#8693 Add VMR build file
  eng/SourceBuild.props
Labels: PR

#8700 Disable nullability in System.Xaml unit test to fix build
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/AcceptedMarkupExtensionExpressionTypeAttributeTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/ArrayExtensionTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/ConstructorArgumentAttributeTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/ContentPropertyAttributeTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/ContentWrapperAttributeTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/DateTimeValueSerializerTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/DependsOnAttributeTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/DictionaryKeyPropertyAttributeTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/MarkupExtensionReturnTypeAttributeTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/NameReferenceConverterTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/NameScopePropertyAttributeTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/ReferenceTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/RootNamespaceAttributeTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/RuntimeNamePropertyAttributeTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/StaticExtensionTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/StringValueSerializerTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/TypeExtensionTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/UidPropertyAttributeTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/XDataTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/XamlSetMarkupExtensionAttributeTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/XamlSetTypeConverterAttributeTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/XmlLangPropertyAttributeTests.cs
Labels: PR

#8717 Updating branding to release/9.0-preview1
  eng/Versions.props
Labels: PR

#8718 Updating branding to release/9.0-preview2
  eng/Versions.props
Labels: PR

#8726 Update triggers
  azure-pipelines.yml
Labels: PR

#8477 GetPattern Null check supporting columns without Datagridowner
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/DataGridCellItemAutomationPeer.cs
Labels: PR

#6632 Eliminate allocation in `StreamAsIStream.Read`
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/StreamAsIStream.cs
Labels: PR, Included in test pass, Community Contribution

#8675 [NRT] Annotate ValueSerializer and related files for NRT
  src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/TypeConverterHelper.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/DateTimeValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Replacements/DateTimeConverter2.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/ms/Internal/Markup/StringValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/ms/Internal/Markup/TypeConverterValueSerializer.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/DateTimeValueSerializerTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/StringValueSerializerTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/ValueSerializerTests.cs
Labels: PR, Included in test pass, Community Contribution
