Repository dotnet/wpf, pull requests merged in 2024-06, with the labels that each got.

#9205 Use new templates to enable internal sources and runtimes
  eng/pipeline-pr.yml
  eng/pipeline.yml
Labels: PR

#9179 Add TargetName to Button's Trigger
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Button.xaml
Labels: PR, Win 11 Theming

#9151 Making resources in parity with WinUI
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Accent.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC1.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC2.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HCBlack.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HCWhite.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
Labels: PR, Win 11 Theming

#9119 Update Corner Radius Resource
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml
Labels: PR, Win 11 Theming

#9214 Revert "Making resources in parity with WinUI"
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Accent.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC1.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC2.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HCBlack.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HCWhite.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
Labels: PR

#9232 Addressed name for previous and next button in calendar control
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Calendar.xaml
Labels: Win 11 Theming

#9255 Fix for "Narrator is announcing incorrect information for expand button"
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Expander.xaml
Labels: PR, Win 11 Theming

#9239 Fix keyboard focus is not navigating to next and previous tab items in tab control
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ScrollViewer.xaml
Labels: PR, Win 11 Theming

#9262 Updating branding to release/9.0-preview6
  eng/Versions.props
Labels: PR

#9265 Normalized mscorlib namespace in fluent xaml files
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/CheckBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/PasswordBox.xaml
Labels: PR, Win 11 Theming

#9269 Update CODEOWNERS
  CODEOWNERS
Labels: PR

#9206 Use generic version of Enum.GetName
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Cursor.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputScopeConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputScopeNameConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemKeyConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RightsManagementResourceHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/SignatureResourceHelper.cs
Labels: PR, Queue for test pass, Community Contribution

#9207 Use generic version of Enum.Parse
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/CursorConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputScopeNameConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/RequestCachePolicyConverter.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Input/KeyConverter.cs
Labels: PR, Queue for test pass, Community Contribution

#9208 Use generic version of Enum.IsDefined
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlReader.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/SafeNativeMethodsCLR.cs
Labels: PR, Queue for test pass, Community Contribution

#9210 Use generic version of Enum.GetValues
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Knowncolors.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/StickyNote/StickyNoteAnnotations.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/Tracing/SpellerCOMActionTraceLogger.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RightsManagementResourceHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/SignatureResourceHelper.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintConfig/PrintSchema.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/DpiAwarenessContext/DpiAwarenessContextHandle.cs
Labels: PR, Queue for test pass, Community Contribution

#8681 Performance Optimization by Reduce reflection assemblies in Utilities.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/Utilities.cs
Labels: PR, Queue for test pass, Community Contribution

#8300 Keep track of selected TabItem for focus
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TabItem.cs
Labels: PR, Queue for test pass, Community Contribution

#8871 Supported MouseAction.None in xaml #8842
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/MouseActionConverter.cs
Labels: PR, Queue for test pass, Community Contribution

#8924 Fix some attributes NRT annotations
  src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/RuntimeIdentifierPropertyAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/AcceptedMarkupExtensionExpressionTypeAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ConstructorArgumentAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ContentWrapperAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/DependsOnAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/DictionaryKeyPropertyAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/NameScopePropertyAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/RootNamespaceAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/UidPropertyAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XamlSetMarkupExtensionAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XamlSetTypeConverterAttribute.cs
Labels: PR, Queue for test pass, Community Contribution

#5610 Improve performance of DynamicResource usages
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceDictionary.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs
Labels: Performance, PR, Queue for test pass, Community Contribution

#9294 Avoid unlocking ComLockableWrapper when server object is already null
  src/Microsoft.DotNet.Wpf/src/PenImc/dll/ComLockableWrapper.hpp
  src/Microsoft.DotNet.Wpf/src/PenImc/dll/PimcManager.cpp
Labels: PR

#9187 Fixed method names in Window XML doc remarks
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
Labels: PR, Community Contribution

#9307 [release/8.0] Switch to dSAS for internal runtimes
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/post-build/publish-using-darc.ps1
  eng/common/templates-official/job/publish-build-assets.yml
  eng/common/templates-official/job/source-build.yml
  eng/common/templates-official/job/source-index-stage1.yml
  eng/common/templates-official/jobs/source-build.yml
  eng/common/templates-official/post-build/post-build.yml
  eng/common/templates-official/steps/enable-internal-runtimes.yml
  eng/common/templates-official/steps/get-delegation-sas.yml
  eng/common/templates-official/steps/get-federated-access-token.yml
  eng/common/templates/job/publish-build-assets.yml
  eng/common/templates/job/source-build.yml
  eng/common/templates/job/source-index-stage1.yml
  eng/common/templates/jobs/source-build.yml
  eng/common/templates/post-build/post-build.yml
  eng/common/templates/post-build/setup-maestro-vars.yml
  eng/common/templates/steps/enable-internal-runtimes.yml
  eng/common/templates/steps/get-delegation-sas.yml
  eng/common/templates/steps/get-federated-access-token.yml
  eng/pipeline-pr.yml
  eng/pipeline.yml
  global.json
Labels: PR

#9306 [release/6.0] Switch to dSAS for internal runtimes
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/templates-official/job/source-build.yml
  eng/common/templates-official/job/source-index-stage1.yml
  eng/common/templates-official/jobs/source-build.yml
  eng/common/templates-official/post-build/common-variables.yml
  eng/common/templates-official/steps/enable-internal-runtimes.yml
  eng/common/templates-official/steps/get-delegation-sas.yml
  eng/common/templates-official/steps/get-federated-access-token.yml
  eng/common/templates/job/source-build.yml
  eng/common/templates/job/source-index-stage1.yml
  eng/common/templates/jobs/source-build.yml
  eng/common/templates/post-build/common-variables.yml
  eng/common/templates/steps/enable-internal-runtimes.yml
  eng/common/templates/steps/get-delegation-sas.yml
  eng/common/templates/steps/get-federated-access-token.yml
  eng/pipeline-pr.yml
  eng/pipeline.yml
  global.json
Labels: PR

#9305 Switch to dSAS for internal runtimes for wpfautomatedtests
  eng/wpfautomatedtests.yml
Labels: PR
