Repository dotnet/wpf, pull requests merged in 2024-07, with the labels that each got.

#9337 Updated .NET Runtime used for running WPF automated tests ( DRTs )
  eng/pipeline-pr.yml
Labels: PR

#9341 Update branding to 6.0.33
  eng/Versions.props
Labels: PR

#9342 Update branding to 8.0.8
  eng/Versions.props
  eng/pipeline-pr.yml
Labels: PR

#9351 Merged all the high contrast themes files into one theme file
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeManager.cs
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC1.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC2.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HCWhite.xaml
Labels: PR, Win 11 Theming

#9368 Replace X509Certificate2 ctor with X509CertificateLoader.LoadCertificate
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/Certificate.cs
Labels: PR

#9367 Added tab navigation control in calendar
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Calendar.xaml
Labels: PR

#9371 Merging internal commits for release/6.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#9370 Merging internal commits for release/8.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#9340 Fixed keyboard focus for DatePicker control
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml
Labels: PR

#9407 Enabling Fluent theme in Windows 10
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
Labels: PR, Win 11 Theming

#9421 Making common resource in parity with WinUI
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
Labels: PR, Win 11 Theming

#9404 Replace accent color resources to use SystemColors.AccentColor
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/DWMColorization.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeManager.cs
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Accent.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Fluent.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
Labels: PR, Win 11 Theming

#9422 Added ThemeGenerator script for Fluent and generated combined Fluent theme resource dictionaries
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeManager.cs
  src/Microsoft.DotNet.Wpf/src/Themes/Generator/ThemeGenerator.Fluent.ps1
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Calendar.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DataGrid.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Expander.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ScrollBar.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Labels: PR, Win 11 Theming

#9425 Combining backdrop disabled and default window styles
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Window.xaml
Labels: PR, Win 11 Theming

#9405 Replace CaseInsensitiveComparer with generics in Speller, remove allocations
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/Speller.cs
Labels: PR, Community Contribution

#9426 Remove Redundant Semicolons
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/StrokeRenderer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/MouseGestureConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispLogic.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndTarget.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/FontFamilyConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/PresentationSource.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/Journaling.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TextAdaptor.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/RtfToXamlReader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextSelection.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/WpfKnownMemberInvoker.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/WpfMemberInvoker.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Navigation/JournalEntry.cs
Labels: PR, Community Contribution

#9229 Additional changes to define Value property of Setter as XAML content property
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref.baseline.txt
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/WpfGeneratedKnownProperties.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/WpfGeneratedKnownTypes.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/KnownTypes.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/StyleXamlParser.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Setter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework.cs
Labels: PR

#9398 Adding Part_ Template parity
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ComboBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/MenuItem.xaml
Labels: PR, Win 11 Theming

#9393 Fixing issues with DynamicResource usage
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceDictionary.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceReferenceExpression.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/DependencyObject.cs
Labels: PR, Community Contribution

#9435 Addressed build failure : ambiguous call to overloaded function
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontCollectionLoader.h
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileEnumerator.h
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileLoader.h
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileStream.h
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/inc/GDIExporter/gdirt.h
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/FontInfo.cpp
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdibitmap.cpp
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdidevice.cpp
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdipath.cpp
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdipen.cpp
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdirt.cpp
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gditextrt.cpp
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/utils.cpp
Labels: PR

#9230 Remove bunch of allocations caused by static arrays by favoring ReadOnlySpan<T>
  src/Microsoft.DotNet.Wpf/src/Common/Graphics/wgx_exports.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/InkSerializedFormat/AlgoModule.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/InkSerializedFormat/InkSerializer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Shaping/Positioning.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Cursor.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/EllipseGeometry.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/LineGeometry.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/RectangleGeometry.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Annotations/Anchoring/LocatorManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/ListMarkerSourceInfo.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridLengthConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridRow.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DocumentViewer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/DataGridRowHeader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedTextBuilder.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/RtfToXamlReader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextEditor.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextPointerBase.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/KnownStrings.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WinEventTracker.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/ContentType.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CompoundFile/RightsManagementEncryptionTransform.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/PackUriHelper.cs
Labels: PR, Community Contribution

#9436 Implemented Application.ThemeMode and Window.ThemeMode properties
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref.baseline.txt
  src/Microsoft.DotNet.Wpf/Directory.Build.Props
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Appearance/WindowBackdropManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FluentThemeState.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeMode.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeModeConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework.cs
  src/Microsoft.DotNet.Wpf/src/Themes/Generator/ThemeGenerator.Fluent.ps1
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR

#9440 Update branding to 9.0.0-rc1
  eng/Versions.props
Labels: PR

#9445 Revert Xunit version
  eng/Versions.props
Labels: PR

#9446 [Release/9.0-preview7] Revert Xunit version
  eng/Versions.props
Labels: PR

#9441 Debug::Assert(false to Debug::Fail
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontCollectionLoader.h
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileEnumerator.h
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileLoader.h
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileStream.h
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdibitmap.cpp
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdibrush.cpp
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdipath.cpp
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdipen.cpp
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdirt.cpp
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gditextrt.cpp
Labels: PR, Community Contribution

#9451 Update acceptance_criteria.md
  Documentation/acceptance_criteria.md
Labels: PR, Community Contribution

#9471 Enable PresentationCore tests
  Microsoft.Dotnet.Wpf.sln
  eng/Versions.props
  src/Microsoft.DotNet.Wpf/src/PresentationCore/OtherAssemblyAttrs.cs
  src/Microsoft.DotNet.Wpf/tests/Directory.Build.props
  src/Microsoft.DotNet.Wpf/tests/UnitTests/Directory.Build.targets
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/PresentationCore.Tests.csproj
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System.Xaml.Tests.csproj
Labels: PR, Community Contribution

#9473 Updated Fluent Theme Generator script
  src/Microsoft.DotNet.Wpf/src/Themes/Generator/ThemeGenerator.Fluent.ps1
Labels: PR, Win 11 Theming

#8868 Added Themes folder with Generic.xaml under net5.0 and net6.0 folders.
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/net5.0/Themes/Generic.xaml
  packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/net6.0/Themes/Generic.xaml
Labels: PR

#9236 Fix for color contrast ratio of chevron button of combo box
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
Labels: PR, Win 11 Theming

#9465 Switch to System.Formats.Nrbf
  eng/Versions.props
  src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/ArrayInfo.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/ArraySingleObject.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/ArraySinglePrimitive.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/ArraySingleString.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/BinaryArray.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/BinaryArrayType.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/BinaryFormattedObject.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/BinaryFormattedObjectExtensions.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/BinaryLibrary.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/BinaryObjectString.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/BinaryReaderExtensions.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/ClassInfo.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/ClassRecord.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/ClassTypeInfo.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/ClassWithId.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/ClassWithMembers.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/ClassWithMembersAndTypes.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/Count.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/IBinaryFormatParseable.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/IRecord.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/Id.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/ListConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/ListConverterHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/MemberPrimitiveTyped.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/MemberReference.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/MemberTypeInfo.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/MessageEnd.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/NullRecord.ObjectNullMultiple.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/NullRecord.ObjectNullMultiple256.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/NullRecord.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/NullableAttributes.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/ObjectNull.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/Record.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/RecordMap.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/SerializationExtensions.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/SerializationHeader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/SystemClassWithMembers.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/SystemClassWithMembersAndTypes.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/BinaryFormat/TypeInfo.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Nrbf/SerializationRecordExtensions.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/DataStreams.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/BinaryFormat/ArrayTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/BinaryFormat/BinaryFormatWriterTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/BinaryFormat/BinaryFormattedObjectTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/BinaryFormat/ClassInfoTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/BinaryFormat/ExceptionTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/BinaryFormat/HashTableTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/BinaryFormat/ListTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/BinaryFormat/MemberTypeInfoTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/BinaryFormat/PointFTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/BinaryFormat/PrimitiveTypeTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/BinaryFormat/RecordMapTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/BinaryFormat/SystemDrawingTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/PresentationCore.Tests.csproj
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/TestUtilities/BinaryFormatTestExtensions.cs
Labels: PR

#9492 Ensure WPF builds against framework SRSF version
  eng/WpfArcadeSdk/tools/TestProjects.targets
  global.json
  src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationCore/ref/PresentationCore-ref.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework-ref.csproj
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj
  src/Microsoft.DotNet.Wpf/src/System.Xaml/ref/System.Xaml-ref.csproj
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/PresentationCore.Tests.csproj
Labels: PR
