Repository dotnet/wpf, pull requests merged in 2024-10, with the labels that each got.

#9221 Replace ArrayList in InputLanguageSource with fixed-size array, reduce allocations
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputLanguageManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputLanguageSource.cs
Labels: PR, Community Contribution

#9222 Replace ArrayList in CursorConverter with preallocated array and reduce allocations
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/CursorConverter.cs
Labels: PR, Community Contribution

#9551 Optimize DependencyProperty lookup/registration performance, remove allocs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/DependencyProperty.cs
Labels: PR, Community Contribution

#9552 Replace boxing Hashtable in AdornerPresentationContext, reduce allocations
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Annotations/Component/AdornerPresentationContext.cs
Labels: PR, Community Contribution

#9439 Reduce allocations while enumerating Speller suggestions and improve performance
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/Speller.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/SpellerError.cs
Labels: PR, Community Contribution

#9676 Optimize conversion of MouseAction enum from/to string, remove allocations
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/MouseActionConverter.cs
Labels: PR, Community Contribution

#9220 Replace Marshal.SizeOf(...) calls for primitive types with sizeof(...)
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/GestureRecognizer/NativeRecognizer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputProcessorProfiles.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/PixelFormat.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/AppSecurityManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Printing/PrintDlgExMarshaler.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/WindowsRuntime/Generated/WinRT/Marshalers.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/ImmComposition.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/InputScopeAttribute.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/PeoplePickerWrapper.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintConfig/FallbackPTProvider.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Ink/Native.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/Condition.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/CommonXSendMessage.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CompoundFile/ContainerUtilities.cs
Labels: PR, Community Contribution

#9711 Improve start-up time by not figuring out NetFX version for AppContext switches
  src/Microsoft.DotNet.Wpf/src/Common/src/System/AppContextDefaultValues.cs
Labels: PR, Community Contribution

#9724 Use string.Equals over string.Compare in ContentType for improved performance
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/ContentType.cs
Labels: PR, Community Contribution

#9363 Reduce ThicknessConverter allocs to minimum and improve conversion performance
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/LengthConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThicknessConverter.cs
Labels: PR, Community Contribution

#9872 Update branding to 6.0.36
  eng/Versions.props
Labels: PR

#9873 Update branding to 8.0.11
  eng/Versions.props
Labels: PR

#9882 Remove SecurityCriticalData/Class
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Classification.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/CommandDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/DefaultTextStore.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputMethod.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputProviderSite.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputReport.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/KeyboardDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/RawKeyboardInputReport.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/RawMouseInputReport.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/StylusLogic.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/TabletDeviceInfo.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerLogic.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerStylusDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerStylusPlugInManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/PenContext.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/PenContextInfo.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/PenContexts.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/PenThreadWorker.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispLogic.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispStylusDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispTabletDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/TextServicesCompartment.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/TextServicesContext.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndAppCommandInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndKeyboardInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndMouseInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndPointerInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndSource.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndStylusInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/ColorContext.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Effects/PixelShader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/GlyphTypeface.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaContextNotificationWindow.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/SourceChangedEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedSchema.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextEditorContextMenu.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextServicesHost.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/XPSS0ValidatingLoader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/DocumentProperties.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/NavigationHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RMPermissions.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/SecurityCriticalData.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/SecurityCriticalDataClass.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/HwndWrapper.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/Dispatcher.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/WindowsBase.csproj
Labels: PR

#9609 Remove unnecessary MarshalLocal.IsTypeVisibleFromCom proxy for code quality
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MarshalLocal.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/WebBrowser.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/DynamicScriptObject.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#9744 Remove obsolete TARGETTING35SP1 preprocessor directive and dead code within
  src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/RuntimeIdentifierPropertyAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/AttachablePropertyServices.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/ObjectWriterContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriterSettings.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlException.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlLanguage.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlSchemaContext.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#9896 [release/9.0] Removing invalid Fluent DataGridColumn styles
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DataGrid.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Servicing-consider

#9521 Replace SecurityHelper.AreStringTypesEqual with string.Equals for code quality
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/AppModel/SiteOfOriginPart.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Navigation/BaseUriHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/AppModelKnownContentFactory.cs
  src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/AddressUtility.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/SecurityHelper.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/BindUriHelper.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#9912 Merging internal commits for release/6.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#9913 Merging internal commits for release/8.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#9915 Add batch file for easier launching of VS
  start-vs.cmd
Labels: PR

#9749 Remove IsPresentationFrameworkVersionLessThan4 property and associated dead code
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Shell/WindowChromeWorker.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/Utilities.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#9678 Make sure Git pre-commit hook directory exists before copying script
  eng/restore-toolset.ps1
Labels: PR

#9757 Remove invalid Fluent DataGridColumn styles
  src/Microsoft.DotNet.Wpf/src/Themes/Generator/ThemeGenerator.Fluent.ps1
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DataGrid.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Community Contribution

#9907 Avoid calling soon-to-be-removed string.Trim(ReadOnlySpan<char>) methods
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/KnownStrings.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/ContentType.cs
Labels: PR

#9936 Updated Intellisense package version to 9.0.0-preview-20241010.1
  eng/Versions.props
Labels: PR

#9952 Fixed ListView content alignment regression
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TabControl.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR

#9903 Remove obsolete FxCop warning suppressions
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/HwndHost.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/DoubleUtil.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/DpiHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/ErrorCodes.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/MessageWindow.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/Utilities.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/Verify.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/FrugalList.cs
  src/Microsoft.DotNet.Wpf/src/Shared/Telemetry/Managed/TelemetryEventSource.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Input.Manipulations/System.Windows.Input.Manipulations.csproj
  src/Microsoft.DotNet.Wpf/src/System.Windows.Input.Manipulations/System/Windows/Input/Manipulations/GlobalSuppressions.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Input.Manipulations/System/Windows/Input/Manipulations/ManipulationVelocities2D.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/GlobalSuppressions.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/SafeReflectionInvoker.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlMemberInvoker.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlTypeInvoker.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/CodeQuality_Approved.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/CodeQuality_Approved.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/MS/Internal/Automation/CodeQuality_Approved.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/ComponentModel/PropertyFilterAttribute.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Interop/ComponentDispatcher.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Interop/MSG.cs
Labels: PR, Community Contribution

#9870 Replace ArrayList with List<GlyphRun> in PtsHost for performance/code quality
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/Line.cs
Labels: PR, Community Contribution

#9330 Remove Marshalling code during Color Translation, reduce allocations
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Color.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/ColorTransform.cs
Labels: PR, Community Contribution

#9862 Remove GenericEnumerator dead code from PresentationCore
  src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/GenericEnumerator.cs
Labels: PR, Community Contribution

#9858 Remove TimelineEnumerator/TimelineTreeEnumerator dead code
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/Subtree.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/TimelineEnumerator.cs
Labels: PR, Community Contribution

#9863 Remove AssemblyFilter dead code as APTCA is not supported
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/AssemblyFilter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
Labels: PR, Included in test pass, Status:Completed, Community Contribution
