Repository dotnet/wpf, pull requests merged in 2024-12, with the labels that each got.

#10133 [.NET 9 ] Fluent Style Fixes : HC.xaml loading, disabled radiobutton UI etc.
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RadioButton.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TabControl.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Servicing-approved, Win 11 Theming

#10136 [release/9.0] Fixes window backdrop and background in Windows 10 and window theme interactions with system changes
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeManager.cs
  src/Microsoft.DotNet.Wpf/src/Themes/Generator/ThemeGenerator.Fluent.ps1
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Window.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Servicing-approved, Win 11 Theming

#10094 Fixing HighContrast theme in Fluent
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
Labels: PR, Win 11 Theming, Port to .NET 9.0

#10120 Fixing window theme changes when system's theme is changed
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeManager.cs
Labels: PR, Win 11 Theming, Port to .NET 9.0

#10132 Matching the list of color resource keys in Light, Dark and HC files for Fluent
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
Labels: PR, Win 11 Theming, Port to .NET 9.0

#10129 Fixing Disabled UI state in radiobutton
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RadioButton.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming, Port to .NET 9.0

#10130 Modified Expander animation mechanism in Fluent to avoid Argument Null Exception
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Controls/AnimationFactorToValueConverter.cs
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Expander.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming

#10159 Fixed typo
  Documentation/docs/using-fluent.md
Labels: PR, Community Contribution

#10167 Start System.Printing test project
  Microsoft.Dotnet.Wpf.sln
  src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/PrintSystemAssemblyInfo.cpp
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Printing.Tests/GlobalUsings.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Printing.Tests/System.Printing.Tests.csproj
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Printing.Tests/System/Printing/IndexedProperties/PrintStringPropertyTests.cs
Labels: PR

#10119 [StyleCleanUp] Addressing SA warnings Part 1
  src/Microsoft.DotNet.Wpf/src/.editorconfig
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/FrugalList.cs
  src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/ReflectionHelper.cs
  src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/XmlCompatibilityReader.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/GlobalSuppressions.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/AttachablePropertyServices.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/ObjectWriterContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/XamlContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/XamlParserContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/IAttachedPropertyStore.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/Reflector.cs
Labels: PR, Status:Completed

#9292 Remove CriticalHandle properties
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/WindowsRuntime/Windows/UI/ViewManagement/InputPane.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputElement.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/PenContexts.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispLogic.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndKeyboardInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndMouseInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndPanningFeedback.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndPointerInputProvider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndSource.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/SecurityMgrSite.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Printing/Win32PrintDialog.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/DocumentViewerHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/CommonDialog.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/HwndHostAutomationPeer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/WindowAutomationPeer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/HwndHost.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/WindowInteropHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/MessageBox.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/PointUtil.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#7485 Remove SafeReflectionInvoker Part 2
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/SafeReflectionInvoker.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlMemberInvoker.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlTypeInvoker.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#4027 Remove redundant static fields to reduce memory usage in XamlTypeInvoker
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlTypeInvoker.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#9215 Replace ArrayList with List<string> in DataObject, reduce some allocations
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#9733 Remove SafeSecurityHelper.GetCultureInfoByIetfLanguageTag proxy for code quality
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/TextFormatting/CultureMapper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Markup/XmlLanguage.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/SafeSecurityHelper.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#9838 Remove dead code in FontSourceCollection/FontSource (+ hollow CAS remnants)
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FamilyCollection.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FontSource.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FontSourceCollection.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/GlyphTypeface.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#9916 Remove internal Pair type in favor of generic tuples
  src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/D3DImage.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Pair.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#10196 Updating PresentationBuildTasksTfm to Net 10
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
Labels: PR

#10197 Fix winforms private package TFM when building inside VMR
  eng/WpfArcadeSdk/tools/SdkReferences.targets
Labels: PR

#10204 Reduce magic numbers in FrugalList.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/FrugalList.cs
Labels: PR, Community Contribution

#10061 [Cleanup] Use named arguments in System.Xaml
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/ObjectWriterContext.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriter.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlTextReader.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/MeScanner.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/XamlAttribute.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Runtime/DynamicMethodRuntime.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Runtime/PartialTrustTolerantRuntime.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/CollectionReflector.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/Reflector.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/TypeReflector.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XmlNamespace.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlMember.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlObjectReader.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlType.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#8203 Add more System.Xaml tests
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/Common/CustomAssembly.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/Common/CustomConstructorInfo.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/Common/CustomMethodInfo.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/Common/CustomType.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/Common/CustomXamlType.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/Common/Optional.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/Common/SubXamlReader.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/Common/SubXamlType.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System.Xaml.Tests.csproj
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/AmbientPropertyValueTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/AttachableMemberIdentifierTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/NamespaceDeclarationTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/Replacements/DateTimeConverter2Tests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/Replacements/DateTimeOffsetConverter2Tests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/Replacements/EventConverterTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/Replacements/TypeListConverterTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/Replacements/TypeTypeConverterTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/Replacements/TypeUriConverterTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/Schema/XamlMemberInvokerTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/Schema/XamlTypeInvokerTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/Schema/XamlTypeNameTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/Schema/XamlTypeTypeConverterTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/Schema/XamlValueConverterTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlBackgroundReaderTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlDirectiveTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlDuplicateMemberExceptionTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlExceptionTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlInternalExceptionTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlLanguageTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlMemberTests.Mocks.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlMemberTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlNodeListTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlNodeQueueTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlObjectEventArgsTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlObjectReaderExceptionTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlObjectReaderSettingsTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlObjectWriterExceptionTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlObjectWriterSettingsTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlParseExceptionTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlReaderSettingsTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlReaderTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlSchemaContextSettingsTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlSchemaContextTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlSchemaExceptionTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlServicesTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlTypeTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlWriterSettingsTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlWriterTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlXmlReaderSettingsTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlXmlWriterExceptionTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Xaml/XamlXmlWriterSettingsTests.cs
Labels: PR, Community Contribution

#9697 Optimize conversion of Key enum from/to string, reduce allocations
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Input/KeyConverter.cs
Labels: PR, Community Contribution

#9853 Replace ArrayList/ICollection used for changelog in CollectionView with generic List
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/CollectionView.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#9943 Remove OleCmdHelper/ISecureCommand dead code (CAS/XBAP leftovers)
  src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/ISecureCommand.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/SecureUICommand.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/IBrowserHostServices.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/OleCmdHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
Labels: PR, Community Contribution
