Repository dotnet/wpf, pull requests merged in 2025-02, with the labels that each got.

#9822 Optimize ResourceContainer/AssemblyLoadEventHandler methods, remove allocs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ResourceContainer.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/ReflectionUtils.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#10144 [StyleCleanUp] Addressing CA warnings Part 1
  src/Microsoft.DotNet.Wpf/src/.editorconfig
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/TaskHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/UidManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/RBNode.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/RBTree.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Interop/InternalDispatchObject.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/XamlToRtfWriter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/DependencyPropertyConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/MarkupExtensionParser.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlReaderHelper.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/ColorTypeConverter.cs
  src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/VisualTreeFlattener.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonKeyTipAndContentSyncHelper.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/GenericTypeNameParser.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/ProxyManager.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WinFormsSpinner.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsContainer.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsMenu.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsRichEdit.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsSpinner.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsSysHeader.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsUpDown.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/AvTrace.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CompoundFile/ContainerUtilities.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/PackUriHelper.cs
Labels: PR

#10405 Create arch neutral packages when building inside the VMR
  packaging/Directory.Build.props
Labels: PR

#10402 Update branding to 9.0.3
  eng/Versions.props
Labels: PR

#10401 Update branding to 8.0.14
  eng/Versions.props
Labels: PR

#10409 Adding Default Style key for Label
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Label.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming

#10404 Remove unnecessary S.R.CompilerServices.Unsafe packageref
  eng/Versions.props
  src/Microsoft.DotNet.Wpf/src/System.Windows.Primitives/System.Windows.Primitives.csproj
  src/Microsoft.DotNet.Wpf/src/WindowsBase/WindowsBase.csproj
Labels: PR

#10411 Fix the ArtifactsPackagingDir on win-x64
  eng/WpfArcadeSdk/tools/Packaging.props
Labels: PR

#10416 fix: spelling of required in gen-api.md
  Documentation/gen-api.md
Labels: PR, Community Contribution

#10410 Fix build binlog overwritten by test step
  eng/pipeline.yml
Labels: PR

#10428 Fix crash if bitmapStream is null
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/BitmapDecoder.cs
Labels: PR, Community Contribution

#10436 Fix crash if bitmapStream is null. Fixes #10390
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/BitmapDecoder.cs
Labels: PR, Community Contribution

#10423 Remove deprecated .Net runtime
  global.json
Labels: PR, Community Contribution

#10430 Sync MilCodeGen to generated code
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/AnimatableTemplate.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/AnimationBaseTemplate.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/AnimationClockResource.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/AnimationResourceTemplate.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/AnimationTemplate.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/AnimationUsingKeyFramesTemplate.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/CommandStructure.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/DiscreteKeyFrameTemplate.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/DuceResource.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/EasingKeyFrameTemplate.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/Elements.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/FrameworkElementTemplate.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/IAnimatableHelper.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/KeyFrameCollectionTemplate.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/KeyFrameTemplate.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/LinearKeyFrameTemplate.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/ManagedEnum.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/ManagedResource.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/ManagedStruct.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/PolySegmentTemplate.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/SplineKeyFrameTemplate.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/renderdata.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/helpers/CollectionHelper.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/helpers/EmptyClassHelper.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/helpers/ManagedStyle.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/helpers/Style.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/xml/Resource.xml
Labels: PR, Community Contribution

#10433 Run MilCodeGen for WindowsBase
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Converters/Generated/Int32RectValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Converters/Generated/PointValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Converters/Generated/RectValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Converters/Generated/SizeValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Converters/Generated/VectorValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/Int32Rect.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/Int32RectConverter.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/Point.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/PointConverter.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/Rect.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/RectConverter.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/Size.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/SizeConverter.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/Vector.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/VectorConverter.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Media/Converters/Generated/MatrixValueSerializer.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Media/Generated/Matrix.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Media/Generated/MatrixConverter.cs
Labels: PR, Community Contribution

#10435 Run MilCodeGen for PresentationFramework
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Generated/FrameworkContentElement.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Generated/FrameworkElement.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/DiscreteKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/EasingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/KeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/LinearKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/SplineKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/ThicknessAnimation.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/ThicknessAnimationBase.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/ThicknessAnimationUsingKeyFrames.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/ThicknessKeyFrameCollection.cs
Labels: PR, Community Contribution

#10337 Disable code analysis for generated code
  .editorconfig
Labels: PR, Community Contribution

#10431 Run MilCodeGen for WpfGfx
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/ResourceModel/Generated/Elements.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/resources/data_generated.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/resources/marshal_generated.cpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/resources/renderdata_generated.cpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/resources/resources_generated.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/uce/generated_process_message.inl
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/uce/generated_resource_factory.cpp
  src/Microsoft.DotNet.Wpf/src/WpfGfx/core/uce/generated_resource_factory.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/exts/cmdstruct.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_command_types.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_command_types.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_commands.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_commands.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_misc.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_misc.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_render_types_generated.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_renderdata_commands.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_resource_types.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_resource_types.h
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wincodec_private_generated.h
Labels: PR, Community Contribution

#10448 Merging internal commits for release/8.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#10449 Merging internal commits for release/9.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#10441 Fixed cursor type in CheckBox, ToolBar and DataGrid
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/CheckBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DataGrid.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ToolBar.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming

#10013 Use ReadOnlyCollection.Empty
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/ManipulationDevice.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/ContainerParaClient.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/FigureParaClient.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/FloaterParaClient.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/FlowDocumentPage.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/PageVisual.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/TextParaClient.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/DocumentPageTextView.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/TextDocumentView.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/TextViewBase.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/UIElementIsland.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Annotations/AnnotationDocumentPaginator.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DocumentViewer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/DocumentViewerBase.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TextChangedEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextFlow.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/MemberReflector.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlMember.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlType.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#9890 Replace PartialList with ReadOnlyCollection
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/BitmapPalette.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/PixelFormat.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/PartialList.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#10474 Update branding to release/10.0-preview3 
  eng/Versions.props
Labels: PR

#10469 Makes Margin and Padding of ListViewItem and ListBoxItem as DynamicResource
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ListBoxItem.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ListViewItem.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming

#10465 ItemsControl and UserControl for fluent
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ItemsControl.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Label.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/UserControl.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming

#10485 Adds reference to ItemsControl and UserControl xaml files in Fluent.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Labels: PR, Win 11 Theming

#10468 Adding style for Thumb in fluent
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Thumb.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Labels: PR, Win 11 Theming

#10478 Change lookup path of binaries: wpf-debug.targets
  Documentation/developer-guide.md
  eng/wpf-debug.targets
Labels: PR

#10494 Force an x64 runtime install
  global.json
Labels: PR

#10499 Adding style for Hyperlink in fluent
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Hyperlink.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Labels: PR

#10501 Adds style for StatusBarItem in fluent
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/StatusBarItem.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Labels: PR, Win 11 Theming

#10504 Adds style for GroupBox in fluent
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/GroupBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Labels: PR, Win 11 Theming

#10511 Adds style for Resizegrip in fluent
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ResizeGrip.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Labels: PR, Win 11 Theming

#6260 [Managed DWrite] Migrate FontCollectionLoader to managed
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/DWriteInterfaces.h
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/Factory.h
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontCollectionLoader.cpp
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontCollectionLoader.h
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/IFontSourceCollection.h
  src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DirectWriteForwarder.cpp
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Text/TextInterface/DWriteInterfaces.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Text/TextInterface/FontCollectionLoader.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Text/TextInterface/IFontSourceCollection.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj
Labels: PR, Queue for test pass, Status:Proposed, Community Contribution

#10516 Make Dynamic Resource Optmization as Opt-Int
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/AppContextDefaultValues.cs
Labels: PR

#10514 Establish Code Coverage for wpf
  Directory.Build.targets
  README.md
  codecov.yml
  eng/CodeCoverage.proj
  eng/CodeCoverage.runsettings
  eng/Testing.targets
  eng/Versions.props
  eng/pipeline-pr.yml
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/ContentType.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/Directory.Build.props
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/PresentationCore.Tests.csproj
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System.Xaml.Tests.csproj
  src/Microsoft.DotNet.Wpf/tests/UnitTests/WindowsBase.Tests/WindowsBase.Tests.csproj
Labels: PR

#10522 Fix DependencyProperty test
  src/Microsoft.DotNet.Wpf/tests/UnitTests/WindowsBase.Tests/System/Windows/DependencyPropertyTests.cs
Labels: PR, Community Contribution

#9395 Simplify CriticalCopyPixels in BitmapSource by removing duplicate type checks
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/BitmapSource.cs
Labels: PR, Included in test pass, Status:Committed, Status:Completed, Community Contribution
