Repository dotnet/wpf, pull requests merged in 2025-05, with the labels that each got.

#10833 Update branding to 9.0.6
  eng/Versions.props
Labels: PR

#10832 Update branding to 8.0.17
  eng/Versions.props
Labels: PR

#10837 Do not check out: self with clean, avoids deleting installed Microbuild plugins
  eng/pipeline.yml
Labels: PR

#10841 Fix crashes in TextBox(es) in Fluent theme
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/PasswordBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RichTextBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming

#10675 [StyleCleanUp] Use ArgumentOutOfRangeException throw helper (CA1512)
  src/Microsoft.DotNet.Wpf/src/.editorconfig
  src/Microsoft.DotNet.Wpf/src/PresentationCore/GlobalSuppressions.cs
Labels: PR, Community Contribution

#6851 Remove the unnecessary fields in DpiHelper
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/DpiHelper.cs
Labels: PR, Included in test pass, Status:Completed, Status:Proposed, Community Contribution

#10848 Merging internal commits for release/8.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#10849 Merging internal commits for release/9.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#9559 Replace boxing IList in HighlightChangedEventArgs and seal derived classes
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Annotations/Component/AnnotationHighlightLayer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/DocumentSequenceHighlightLayer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/DocumentSequenceTextContainer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedDocument.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FlowDocument.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/HighlightChangedEventArgs.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/Highlights.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/SpellerHighlightLayer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextSelectionHighlightLayer.cs
Labels: PR, Included in test pass, Status:Completed, Status:Proposed, Community Contribution

#10844 Replace arch-specific package properties with arch neutral ones
  eng/Tools.props
  eng/Version.Details.xml
  eng/Versions.props
  eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.targets
  global.json
Labels: PR

#10517 Adding simsun-extg font to support more character
  src/Microsoft.DotNet.Wpf/src/PresentationCore/Fonts/GlobalUserInterface.CompositeFont
Labels: PR

#9532 Replace boxing Hashtable in ManagedWndProcTracker with Dictionary<K, V>
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/ManagedWndProcTracker.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#9778 Optimize parsing/conversion of TextDecorations from string, reduce allocations
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/TextDecorationCollectionConverter.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#9926 Optimize assembly/namespace pair creation and updating in XamlSchema
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/AssemblyNamespacePair.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlNamespace.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlSchemaContext.cs
Labels: PR, Included in test pass, Status:Completed, Status:Proposed, Community Contribution

#9946 Replace ArrayList in InputProcessorProfiles with fixed-size array, reduce allocations
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputProcessorProfiles.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#10862 Common Fluent.xaml for System ThemeMode
  src/Microsoft.DotNet.Wpf/src/Themes/Generator/ThemeGenerator.Fluent.ps1
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Labels: PR, Win 11 Theming

#10866 Implemented shorthand syntax for ColumnDefinitions and RowDefinitions
  src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref.baseline.txt
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ColumnDefinition.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ColumnDefinitionCollectionConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Grid.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/RowDefinition.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/RowDefinitionCollectionConverter.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/WpfGeneratedKnownProperties.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework.cs
Labels: PR

#10864 Update Branding to Preview 6
  eng/Versions.props
Labels: PR

#10865 Fixed TabItem MinWidth issue
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TabControl.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Labels: Win 11 Theming

#10863 Fixed ToolTip Fluent Style and Resources
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ToolTip.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Labels: PR, Win 11 Theming

#10878 Fix ComboBox popup content to allow grouping in Fluent
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ComboBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Community Contribution, Win 11 Theming

#10887 Fix(Fluent): TextBox invalidation style
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Labels: PR, Win 11 Theming
