Repository dotnet/wpf, pull requests merged in 2025-04, with the labels that each got.

#9361 Spanify AntiFormat function in AvTrace, decrease allocations, improve perf
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/AvTrace.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#10301 [StyleCleanUp] ThreadStatic fields should not use inline initialization (CA2019)
  src/Microsoft.DotNet.Wpf/src/.editorconfig
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/Win32/UnsafeNativeMethodsPenimc.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Interop/TipTsfHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/StylusLogic.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/StylusTouchDeviceBase.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResourceKey.cs
  src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/TextSearchInternal.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Freezable.cs
Labels: PR, Community Contribution

#9954 Remove array/object allocs during Alt+Numpad composition, improve performance
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/TextCompositionManager.cs
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsCLR.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#9883 Improve font performance in FamilyCollection.GetFontFromFamily
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FamilyCollection.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#10693 Update branding to 8.0.16
  eng/Versions.props
Labels: PR

#10694 Update branding to 9.0.5
  eng/Versions.props
Labels: PR

#10683 [StyleCleanUp] Fix misplaced using directives in CSP (IDE0065)
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Generated/ToleranceTypeValidation.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/helpers/ManagedStyle.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_command_types.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_commands.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_misc.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_resource_types.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/tools/csp/CsPrimeParser.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/tools/csp/CsPrimeRuntime.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/tools/csp/GlobalUsings.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/tools/csp/MainClass.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/tools/csp/Project.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/tools/csp/TempDirectory.cs
  src/Microsoft.DotNet.Wpf/src/WpfGfx/tools/csp/csp.csproj
Labels: PR, Community Contribution

#9468 Modify AvTrace call chain to use params ReadOnlySpan<object> instead of an array
  eng/WpfArcadeSdk/tools/CodeGen/AvTrace/AvTraceMessages.tt
  src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Generated/AvTraceMessages.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/EventRoute.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Generated/AvTraceMessages.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/TraceData.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/AvTrace.cs
  src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/Generated/AvTraceMessages.cs
Labels: PR, Included in test pass, Status:Completed, Community Contribution

#10637 Add test coverage for public API surface of KeySplineConverter
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/Media/Animation/KeySplineConverter.Tests.cs
Labels: Test or Test Infrastructure, PR, Community Contribution

#10632 Add test coverage for public API surface of BrushConverter
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/Media/Generated/BrushConverter.Tests.cs
Labels: Test or Test Infrastructure, PR, Community Contribution

#10633 Add test coverage for public API surface of ColorConverter
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/Media/ColorConverter.Tests.cs
Labels: Test or Test Infrastructure, PR, Community Contribution

#10710 fix: Fix typo mistake committed
  src/Microsoft.DotNet.Wpf/specs/tooltip.md
Labels: PR, Community Contribution

#10267 Avoid zero-length array allocations and storing them in static fields (CA1825)
  src/Microsoft.DotNet.Wpf/src/.editorconfig
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsTable/RowSpanVector.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/WindowsRuntime/Generated/WinRT/GuidGenerator.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/GridViewAutomationPeer.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/InkCanvas.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Slider.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextSchema.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlTypeMapper.cs
  src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlMemberInvoker.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/Schema.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/UiaCoreApi.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/CacheRequest.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/MSAANativeProvider.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsRichEdit.cs
  src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/ControlType.cs
Labels: PR, Community Contribution

#9470 Fix WriteableBitmap's Write/CopyPixels (Clone) to support up to 4GB backbuffers
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/BitmapSource.cs
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/WriteableBitmap.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/Media/Imaging/WriteableBitmap.Tests.cs
Labels: PR, Included in test pass, Status:Committed, Status:Completed, Community Contribution

#10303 Use source-generated regex instead of runtime compilation (SYSLIB1045)
  src/Microsoft.DotNet.Wpf/src/.editorconfig
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/UidManager.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/WinRTSpellerInterop.cs
Labels: PR, Community Contribution

#10722 Don't redistribute inbox msbuild dependencies
  eng/Versions.props
  src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj
Labels: PR

#9463 Try fix EventRoute weak memory leak
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/EventRoute.cs
Labels: PR, Servicing-approved, Included in test pass, Status:Completed, Status:Proposed, Community Contribution

#10741 Merging internal commits for release/9.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#10744 Fixes TreeViewItem chevron arrow orientation when FlowDirection is RightToLeft
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TreeViewItem.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming

#10742 Merging internal commits for release/8.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: PR

#10732 Fix DataObject SetData methods inaccordance to previous implementation
  src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs
Labels: PR

#10752 Added text control common resources and brushes
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming

#10753 Add Resource Dictionary Tests
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Tests/GlobalUsings.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Tests/PresentationFramework.Tests.csproj
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Tests/System/Windows/ResourceDictionaryTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Tests/System/Windows/Resources/SampleResourceDictionary.xaml
Labels: PR

#10735 Fixed MenuItem Header alignment wrt to Icons
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/MenuItem.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming

#10754 Add DataObject SetData tests
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/DataObjectTests.cs
Labels: PR

#10761 Replace FluentAssertions with AwesomeAssertions
  eng/Versions.props
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/PresentationCore.Tests.csproj
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Fluent.Tests/PresentationFramework.Fluent.Tests.csproj
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Tests/PresentationFramework.Tests.csproj
  src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Printing.Tests/System.Printing.Tests.csproj
  src/Microsoft.DotNet.Wpf/tests/UnitTests/WindowsBase.Tests/WindowsBase.Tests.csproj
Labels: PR, Community Contribution

#10766 Added missing TextControl brushes
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming

#10765 Added Fluent theme resource dictionary tests
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Fluent.Tests/GlobalUsings.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Fluent.Tests/PresentationFramework.Fluent.Tests.csproj
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Fluent.Tests/ResourceTests/FluentResourceDictionaryTests.cs
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Fluent.Tests/System/Windows/Controls/ButtonTests.cs
Labels: PR, Win 11 Theming

#10783 Null Annotate PresentationCore ref
  src/Microsoft.DotNet.Wpf/src/PresentationCore/ref/PresentationCore.cs
Labels: PR, area-clipboard

#10781 Add DataObject tests
  src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/DataObjectTests.cs
Labels: PR

#10788 Adds ItemsPresenter in Menu
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Menu.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming

#10768 Fixes the layout and resource usage for PasswordBox
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/PasswordBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming

#10756 [Fluent] Fixes mulitple issues is TextBox and TextBoxBase styles
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming

#10688 [Fluent] Fixes multiple issues in DatePicker style
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming

#10532 Improving DynamicResource performance (second try)
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006KeyRecord.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceDictionary.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/StyleHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs
Labels: PR, Community Contribution

#10793 Fixes layout issues in RichTextBox style for Fluent theme
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RichTextBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR

#10792 Branding for Preview 5
  eng/Versions.props
Labels: PR

#10795 Adds trigger for disabled state for Thumb
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Thumb.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR, Win 11 Theming

#10794 Ignore Dynamic Resource Opt out Preferences
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/AppContextDefaultValues.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceDictionary.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceReferenceExpression.cs
Labels: PR

#10797 Sync release/preview4 with latest changes
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/AppContextDefaultValues.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006KeyRecord.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceDictionary.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceReferenceExpression.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/StyleHelper.cs
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/PasswordBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR

#10798 Sets SelectionBrush for TextBox and other controls
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/PasswordBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RichTextBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
  src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Labels: PR

#10689 Avoid obsoletion warning suppression in ActiveXHost
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/ActiveXHost.cs
Labels: PR, Community Contribution

#10666 Remove WinRT ReflectionHelper dead code (compiled, not used)
  src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj
  src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
  src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/WindowsRuntime/ReflectionHelper.cs
Labels: PR, Community Contribution

#10819 Update CODEOWNERS
  CODEOWNERS
Labels: PR
